### ISSUE TITLE
JS ERROR: TypeError: content is null

### ISSUE THREAD

**Issue by satriani-vai** [Tudmotu/gnome-shell-extension-clipboard-indicator#100]
`JS ERROR: TypeError: content is null
ClipboardIndicator<._updateButtonText@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:95:1
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
ClipboardIndicator<._onPrivateModeSwitch/<@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:460:29`

**Comment by Tudmotu** [comment]
Thanks for reporting!
Seems like a simple ``!content || ...`` will suffice there. Will try to fix that soon. @sVerentsov if you can fix this, that would be awesome :)

**Comment by satriani-vai** [comment]
`JS ERROR: TypeError: that.historySection is undefined
                                            ClipboardIndicator<._onSettingsChange@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:509:9
                                            wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22`

**Comment by sVerentsov** [comment]
@satriani-vai I would suggest you creating another issue for that since it is not connected with "content is null". Also,  it would help if you post more info about when this bug appear or steps to reproduce
.
