### ISSUE TITLE
No POT file

### ISSUE THREAD

**Issue by pkomur** [Tudmotu/gnome-shell-extension-clipboard-indicator#105]
Please create translation template POT file, to facilitate the translation update.

**Comment by Tudmotu** [comment]
Hi,
There is a POT file:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/clipboard-indicator.pot

**Comment by pkomur** [comment]
OK. I found it, but it is out of date. Look at #106 .
