### ISSUE TITLE
FR: Directly paste from list

### ISSUE THREAD

**Issue by pat-richter** [Tudmotu/gnome-shell-extension-clipboard-indicator#109]
I would like to not only set an item as "active" (and push it to my clipboard), but paste it directly in the currently focused field.

An example use case is:
[Shortcut] to open the list
[Arrow down]
[Arrow down]
[Arrow down]
[Shortcut] to paste the current entry (or maybe just "Enter")

This would remove the additional step of Ctr+V the value.

**Comment by monkeydri** [comment]
@Tudmotu I will try to implement it, at least for Xorg it should not be this hard.

**Comment by Tudmotu** [comment]
Sounds from that thread that it's not really possible, right?
In any case, feel free to give it a try! I would try to do this on Wayland tho, since Xorg is going to disappear soon. Maybe Wayland has an option to fake ctrl+v calls somehow. I must admit I have no clue how to do that.. :sweat_smile:

**Comment by komakino** [comment]
@Tudmotu ClipIt uses xdotool so as long as you can run shell commands, it should be no problem with that tool. `/bin/sh -c 'xdotool key ctrl+v'`

**Comment by daf121** [comment]
@komakino @Tudmotu Any luck using xdotool ? Anyone tried? :)

**Comment by daveflr** [comment]
Yeah, I need this feature too, any advance of this?

**Comment by gpothier** [comment]
Hi, I created a fork of this repo (https://github.com/gpothier/gnome-shell-extension-clipboard-indicator) and adapted @tatums pull request to the current version of the extension (and replaced `xdotool type` by `xdotool key` to simulate a ctrl+v press). This does not address the issues raised by @Tudmotu in the PR (namely, it only works in X11 and requires xdotool), so I don't know if it is worthwhile to create a new PR. However, it works for me.

**Comment by PrOF-kk** [comment]
Looks like there's an xdotool "clone" that works independently of the window manager: [ydotool](https://github.com/ReimuNotMoe/ydotool), but there might be issues with licensing as it's under AGPLv3

**Comment by SUPERCILEX** [comment]
Hey folks, this is available in a re-written version of the extension: https://github.com/SUPERCILEX/gnome-clipboard-history.
