### ISSUE TITLE
[Feature Request] Paste on click

### ISSUE THREAD

**Issue by monkeydri** [Tudmotu/gnome-shell-extension-clipboard-indicator#111]
This would be great if click on Clipboard Indicator menu would result in text being pasted on the current input, such as with other clipboard managers like [ClipIt](https://github.com/CristianHenzel/ClipIt).

Currently clicked text is put "at the top" of the clipboard history stack and can then be pasted (ctrl+v).

**Comment by Tudmotu** [comment]
Sounds like a nice feature to have, but unfortunately at the moment I have no time to add such a feature. :\
If anyone wants to try and implement it, I would be happy to merge it :)
I would add it as a "paste" button on every entry, that when clicked pastes the data.
I am not really sure how to do that tho, or if it's even possible as a gnome extensions.

**Comment by monkeydri** [comment]
Funny @netzaffin opened an issue for the same feature almost at the same time !

duplicate of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/109
