### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by orschiro** [Tudmotu/gnome-shell-extension-clipboard-indicator#112]
This is such a brilliant extension!

Do you plan to add support for images?

Storing and pasting images from clipboard is quite essential for me and maybe others, too.

**Comment by orschiro** [comment]
Posted a bounty for this. :-)

https://www.bountysource.com/issues/54210016-support-for-images

**Comment by Tudmotu** [comment]
Hi @orschiro :)
Unfortunately lately I did not have time to work on this extension. Most of the latest features were implemented by community members.

If no one takes a look at it, I will probably get to it some when, but could take a while.

**Comment by orschiro** [comment]
Hey @Tudmotu no problem! 

> Most of the latest features were implemented by community members.

Maybe someone from the community has an idea how to implement this one. :-)
