### ISSUE TITLE
[Feature Request] Keep/persist entries as favs

### ISSUE THREAD

**Issue by b1tdust** [Tudmotu/gnome-shell-extension-clipboard-indicator#113]
I love this extension! It would be awesome allow keeping some entries as favs so the user don't loose them when the historial get full over the time. Also it could persist these favs entries.

Regards!

**Comment by Tudmotu** [comment]
OK, seems like I forgot to upload this feature, but it was implemented by @freeroot already.
I have uploaded a new version to e.g.o and hopefully in the next days you will be able to update.
