### ISSUE TITLE
Select starred item, does not show up in top panel

### ISSUE THREAD

**Issue by orschiro** [Tudmotu/gnome-shell-extension-clipboard-indicator#117]
A starred element was in clipboard but was not shown in the top bar. 

Screencast: https://youtu.be/9TnmY-NZqoA

Tested on Fedora 27 and GNOME Shell 3.26.2.

**Comment by Tudmotu** [comment]
I don't accept donations, but thank you for the offer :)

**Comment by sVerentsov** [comment]
Failed to reproduce on same versions of Fedora and Gnome Shell. May there be some conficts with other clipboard management software?

**Comment by orschiro** [comment]
@sVerentsov thanks for testing! Haven't seen this issue again since upgrading to GNOME 3.28. Shall we close this and I report back in case it occurs again?

**Comment by pothos** [comment]
Top bar content update was not triggered after removing the first list entry (currently in clipboard) and then selecting another element in the list.

**Comment by orschiro** [comment]
I found a reliable way to reproduce this!

Screencast: https://drive.google.com/file/d/1M1aUF8Rh0uChXQ-jGU0iwvFxQlX7E9Jy/view

1. Select a starred item
2. Paste it

It should update the top panel content but instead it's showing the second to last item. 

Please confirm.
