### ISSUE TITLE
QtPass copy and clear clipboard

### ISSUE THREAD

**Issue by FiloSpaTeam** [Tudmotu/gnome-shell-extension-clipboard-indicator#119]
Using QtPass i tryied to copy password with autoclean function after 10 seconds.
I thought it was a bug of QtPass but the clipboard is really clean up and this extension has my password visible

**Comment by sVerentsov** [comment]
By "visible" you mean having at visible in top bar (if displaying content in top bar is enabled) or in history?

**Comment by FiloSpaTeam** [comment]
In top bar is visible the icon. When i click above, it show the history, i thinks, but it's been cleared by QtPass because i tried to paste with Ctrl + v and middle click.

**Comment by sVerentsov** [comment]
It shows the history of clipboard, it is true. Clipboard do not have history, extension just saves what was in clipboard. So, QtPass clears clipboard only, and your password is still saved in history. It is impossible to detect, whether content of the clipboard is password or not, but you can enable Private Mode when you want to copy paste your password and disable it after.

**Comment by Tudmotu** [comment]
Hi @FiloSpaTeam ! Thanks for reporting :)
There are already issues similar to this here, though no real solution as of now.

A workaround that might help -
Clipboard Indicator checks the clipboard content every half a second.
You can increase this to up to 5 seconds in the settings (Under "Refresh Interval", put 5000). It should then be less likely that Clipboard Indicator picks up the password before QtPass erases it.

Let me know if it helps :)

**Comment by sVerentsov** [comment]
Also it is possible to add a feature of "blacklist": user can specify strings that will be ignored by extension. These strings to be stored in SHA, so I suppose it will be secure enough for ignoring passwords.

**Comment by Tudmotu** [comment]
Interesting idea..

**Comment by FiloSpaTeam** [comment]
Surely blacklist can be a good option for someone that has one or two password. But i have more than 120 password and i change them frequently lol
I need to try the workaround :)

**Comment by bhavin192** [comment]
I'm using [`pass`](https://www.passwordstore.org/), which is command line tool. In this case a simple command to enable the private mode will do the trick. So one does not have to go to the top bar and enable the private mode using mouse.

**Comment by Tudmotu** [comment]
Closing this in favor of #46.
