### ISSUE TITLE
Shortcuts don't work after lock screen

### ISSUE THREAD

**Issue by sojusnik** [Tudmotu/gnome-shell-extension-clipboard-indicator#12]
Hey!

The keyboard shortcuts in your extension refuse to work after Gnome's lock screen is activated, either manually or after a certain time. Curiously, they start to work after the Gnome Shell is reloaded (Alt+F2 and then "r"). 

What's the best way to debug this issue?

Using Ubuntu Gnome 14.10 (with off. gnome 3 ppa) and the latest version of your extension, installed via https://extensions.gnome.org/.

Shell version: 3.12.2
Extension version: 8

Best wishes!

**Comment by Tudmotu** [comment]
Interesting! I noticed they stop working after some time, but couldn't reproduce this. Thanks!

Regarding debug - there is no easy way that I know of other then logging.
If you want to know where to look - this is probably somewhere in lines 310-390 (extension.js). Maybe the ``_bindShortcut()`` method.

https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L338

**Comment by sojusnik** [comment]
Since I don't have any programming skills at all, I doubt that I could
understand and improve the code to solve this issue.

What do you exactly mean by logging?

2015-03-11 15:16 GMT+01:00 Yotam Bar-On <notifications@github.com>:

**Comment by Tudmotu** [comment]
OK, no problem. I'll take a look at this myself.
In the meantime, I don't have any workaround to suggest other than restarting the shell :\

Apologies
