### ISSUE TITLE
Disable specific keyboard shortcut?

### ISSUE THREAD

**Issue by orschiro** [Tudmotu/gnome-shell-extension-clipboard-indicator#121]
Hey @Tudmotu while I do like the keyboard shortcuts I would like to disable "Clear history" specifically. 

Is there any way to not assign shortcut to a specific function?

Thanks!

**Comment by izhakjakov** [comment]
+1

**Comment by izhakjakov** [comment]
@orschiro BTW I was able to achieve this using dconf and assigning garbage instead of the schema

**Comment by orschiro** [comment]
@izhakjakov could you explain how you did it? Thanks!

**Comment by Tudmotu** [comment]
Go to the settings and click to change the shortcut - then press backspace.
Does that disable it?

**Comment by orschiro** [comment]
@Tudmotu it does. Thanks for the solution! :-)

**Comment by Tudmotu** [comment]
Sure thing :slightly_smiling_face:

**Comment by izhakjakov** [comment]
@orschiro You first need to customized the shortcut you DON'T want then go to /org/gnome/shell/extensions/clipboard-indicator/clear-history and change the value to something invalid ['gaagusv'] or even just ['']
That said I think @Tudmotu solution is the proper way to do it

Yotam kapara can you maybe put a comment in the settings so people will know that backspace disables the hotkey?

**Comment by orschiro** [comment]
> Yotam kapara can you maybe put a comment in the settings so people will know that backspace disables the hotkey?

Yeah, that's a good idea! :-)

**Comment by Rafal-Spryszynski** [comment]
The proposed solution isn't working for me (Ubuntu 18.04.1 LTS). Backspace isn't disabling the shortcut. 

I barely see any options in Dconf Editor. There is a message "Keys not defined by a schema".
I see display-mode, enable-keybindings, history-size, and notify-on-copy options only.
When I click on any option there is a warning "No schema available".

It would be nice to be able to change the shortcuts.
