### ISSUE TITLE
Last version doesn't respect "Remove Dropdown Arrows" extension

### ISSUE THREAD

**Issue by simonbcn** [Tudmotu/gnome-shell-extension-clipboard-indicator#124]
```
Arch Linux
GNOME Shell 3.28.1
```
I have installed "[Remove Dropdown Arrows](https://extensions.gnome.org/extension/800/remove-dropdown-arrows/)" extension.
Clipboard Indicator shows the dropdown arrow with last version, before it worked. 
If I disable/enable this extension or _Remove Dropdown Arrows_ extension, it works. But when I enter in gnome session, it shows it.
I don't know if the bug is in this extension or in _Remove Dropdown Arrows_.

**Comment by Tudmotu** [comment]
This sounds like a racing condition bug with "Remove Dropdown Arrows" extension.
I'm closing this.
