### ISSUE TITLE
Toggle menu

### ISSUE THREAD

**Issue by androklis** [Tudmotu/gnome-shell-extension-clipboard-indicator#128]
Hello, I there is an issue regarding toggle menu. When I click on the menu nothing happens, the same behavior is with the keyboard shortcut.
Please advise.

**Comment by Tudmotu** [comment]
Hi @androklis,
Did this happen right after installing the extension or after you have already been using it for a while?
Did you try to uninstall/reinstall?
Unfortunately I do not know of a similar issue, so it's a bit hard for me to help.
