### ISSUE TITLE
Focused text entry looks a bit odd with adapta nokto theme

### ISSUE THREAD

**Issue by memeplex** [Tudmotu/gnome-shell-extension-clipboard-indicator#129]
# Unfocused

![Unfocused](https://user-images.githubusercontent.com/2845433/41434090-0f573834-6ff1-11e8-9407-7905ae11bfdc.png)
# Focused

![Focused](https://user-images.githubusercontent.com/2845433/41433956-ac3d0b02-6ff0-11e8-8646-5e34775f087e.png)

**Comment by Tudmotu** [comment]
Hi @memeplex I apologize but you would have to open an issue with the theme. This is out of the control of this extension.
