### ISSUE TITLE
New version distorts elements in the Gnome Shell

### ISSUE THREAD

**Issue by sojusnik** [Tudmotu/gnome-shell-extension-clipboard-indicator#13]
Hey,

after the recent update of your extension on the gnome's extension site, some graphical elements in the Gnome Shell are distorted, have a look [here](http://i.imgur.com/Ngzd1qC.png) and [here](http://i.imgur.com/SWOLbRl.png).

Using Ubuntu Gnome 14.10 with Gnome 3.12 (and some 3.14 packages from the off. Gnome 3 repo in Launchpad). The theme is called Numix and is easily installable with [this](http://satya164.deviantart.com/art/Gnome-Shell-Elegance-Colors-305966388) little app.

Best!

**Comment by Tudmotu** [comment]
Oops! I made some changes to the styles following 3.16, this probably broke earlier versions... :\

Thank you for reporting :)
I'll take a look at it.

**Comment by sojusnik** [comment]
The up-to-date version has still broken delete icons in your extension.

**Comment by Tudmotu** [comment]
Yes, I know. I haven't fixed it yet cause I need a machine with 3.14 to verify it. :\
