### ISSUE TITLE
This extension adds a noticeable delay when starting gnome-shell

### ISSUE THREAD

**Issue by terencode** [Tudmotu/gnome-shell-extension-clipboard-indicator#131]
My gnome-shell with all extension except this one enabled starts in about 4 seconds with 17 extensions enabled.
Adding yours makes it up to 20 seconds, the equivalent of having 85 extensions enabled.

What could cause such a difference?

**Comment by Tudmotu** [comment]
Maybe your cache file is very large.
In the settings page - what are the values for:
1. History Size
1. Max cache file size

Also - when did you update the extension last time? Could it be that it's a very old version?

**Comment by terencode** [comment]
I'm using the latest version from the gnome-shell extension website.

1. History Size: 50
2. Max cache file size 1024
