### ISSUE TITLE
Selecting text does not add it in the clipboard

### ISSUE THREAD

**Issue by cactux** [Tudmotu/gnome-shell-extension-clipboard-indicator#135]
In Unix (and Linux), selecting text directly puts it in a kind of clipboard, then you can paste it somewhere else with the middle click (or both left+right clicks).
It would be great to have this Gnome extension the option to manage these texts too. Once you are used to this, it is far more efficient than CTRL+C, CTRL+V.

**Comment by Tudmotu** [comment]
Hi @cactux :smiley: 
Please see #8, which is exactly the same request.
I have been going over #120 which could advance us in that direction, but it might take some time still.
I'm gonna close this issue, but please check out #8 and see if you have any more input or ideas.

Thanks!

**Comment by cactux** [comment]
Thanks, I subscribed to #8 and I'll comment there.
