### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by RaphaelRochet** [Tudmotu/gnome-shell-extension-clipboard-indicator#14]
Could you add translation support ?

**Comment by Tudmotu** [comment]
I would need to learn how to do that, but I believe it's possible.
I assume you want the 'clear history' and 'settings' buttons translated, as well as the field-names in the settings page, correct?

**Comment by RaphaelRochet** [comment]
Correct ;)

I will provide French translations if needed.

If you prefer, I can also do it myself and send a pull request ?

Le mar. 21 avr. 2015 à 17:27, Yotam Bar-On <notifications@github.com> a
écrit :

**Comment by Tudmotu** [comment]
If you want to do it, I would very much appreciate it :)

**Comment by RaphaelRochet** [comment]
Here it is.
To create a new translation, use the .pot file as a template, create a new subfolder in locale, and name the compiled .mo file 'clipboard-indocator.mo' in that new subfolder.
Using poedit this is very easy. (http://poedit.net/)
