### ISSUE TITLE
'<foo@bar>' is not pasted in gmail compose

### ISSUE THREAD

**Issue by elmarco** [Tudmotu/gnome-shell-extension-clipboard-indicator#140]
For some reason, gmail doesn't like the content of the extension clipboard.

I suspect the text format / encoding isn't raw and gmail interprets it as an email address or filter it out for some reason.

Let me know if you need more details

thanks for the great extension

**Comment by damjad** [comment]
For me, it's working fine.
I've tried a couple of scenarios:

- copied an email from a plain text file
- copied an email from a webpage
- copied an email from Gmail message body

**Comment by damjad** [comment]
Sorry, I wasn't clear enough before.
I've tried different sources for copying the email id in the format you specified _<foo@bar.com>_ and pasted it in the message body as well as the _To_ box. 

For me, it is working fine.
![screenshot from 2018-10-16 18-08-30](https://user-images.githubusercontent.com/16019308/47099298-4820aa00-d235-11e8-94c8-a8965719ccbf.png)

I'm using the default (Xorg) for Ubuntu 18.04.

**Comment by JohJohan** [comment]
I think this issue can be closed as @damjad confirmed its working and @elmarco isn't replying anymore

**Comment by Tudmotu** [comment]
Thanks @JohJohan
