### ISSUE TITLE
Extension not displaying when title bar placed at bottom.

### ISSUE THREAD

**Issue by apurva91** [Tudmotu/gnome-shell-extension-clipboard-indicator#148]
I installed a gnome shell extension dash-to-panel, which basically merges the top title bar and the dock bar 
The clipboard manager doesn't show the clipboard history as shown in the image while all the other extensions work fine. I think it is not positioned dynamically leading to creating a popup only in the bottom of it.
![screenshot from 2018-12-05 11-01-56](https://user-images.githubusercontent.com/25482647/49492343-e3212200-f87d-11e8-9c97-b2877a25f51f.png)

**Comment by nlpsuge** [comment]
Same here.

I'm using dash-to-panel, too.

This happens frequently in my case.

After setting 'Panel screen position' to Top or setting back to Bottom, clicking the clipboard icon can pop up the history window. This perhaps is a workaround temporarily...

**Comment by SuperSamus** [comment]
I use Just Perfection to move the bar to the bottom and I have no problem.
![Screenshot from 2021-12-28 01-31-54](https://user-images.githubusercontent.com/40663462/147515611-2c0a7dae-d3c6-4967-826c-6e29025d62d7.png)
