### ISSUE TITLE
[Feature request] Make icon more compact

### ISSUE THREAD

**Issue by zhabba** [Tudmotu/gnome-shell-extension-clipboard-indicator#150]
Currently icon looks like two separate icons: main icon and some triangle. Removing that triangle would make icon looking more common and save some panel space.

**Comment by Tudmotu** [comment]
This is the intended behavior, as this is the convention of dropdowns in the top bar. You can notice that all other dropdowns behave similarly. I am open to the idea of allowing to remove the arrow in the settings, but currently have no time to work on something like that. :\

**Comment by zhabba** [comment]
@Tudmotu thanks a lot for clarification, now I see logic of that arrow presence.

**Comment by farverio** [comment]
@Tudmotu I wonder if you might consider exploring removing this triangle again, either by default or an option. I see more and more apps moving away from the arrow as the real estate between Gnome's center clock and main power/wifi/sound tray on the right of the top bar.

I looked at the source code and could likely take a stab at moving this in the right direction, but am not familiar with testing GTK apps or anything. I'd like to think i could help with an initial proposal but not so much on the QA side? Let me know -- big fan of this app but its always been a bit of a nuisance that it takes up so much more real estate!

Your thoughts are greatly appreciated :)
