### ISSUE TITLE
ENTER key not choosing selected item

### ISSUE THREAD

**Issue by pburney** [Tudmotu/gnome-shell-extension-clipboard-indicator#156]
Hi Tudmotu,

Thank you for this great piece of software! I'd been a Didion and GPaste user before but your simple indicator is just what I need.

I'm currently experiencing an issue where the "ENTER/RETURN" key does not select the item, but instead I need to click on it with the mouse. I think this should be working based on this request:

https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/9

Unlike this issue, my arrow keys are working just fine to navigate the list:

https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/84

Thanks for any help you can offer!

-Paul

OS: Ubuntu 18.04.2 LTS
kernel: 4.18.20-041820-generic
$XDG_CURRENT_DESKTOP: GNOME
$GDMSESSION: gnome

**Comment by TakedoNick** [comment]
So is there going to be a fix? This is a major issue as it is forcing me to reach out for the mouse everytime I hover over a selection.

**Comment by pburney** [comment]
Any thoughts @Tudmotu ? I'm happy to help test a development build if needed. Thank you.
