### ISSUE TITLE
[Feature Request] Export history button

### ISSUE THREAD

**Issue by protiumx** [Tudmotu/gnome-shell-extension-clipboard-indicator#160]
Hello. First I want to thank you for your time and building this pretty useful extension.
I use it heavily to store large commands I use in different dev environments. Now I'm backing up those commands and I think that a button to export all the history would be great. Or maybe export only the pinned values.

I'm not familiar with gnome extension development but if I find the time I'll try to drop a PR for this. In the mean time I let this here.

Thanks!

**Comment by Syzygianinfern0** [comment]
I am stuck at this same place. Do you know how to solve it?

**Comment by SUPERCILEX** [comment]
You can find the history in `~/.cache/clipboard-indicator@tudmotu.com/`. I don't see the need for exports since you can favorite items so they stay forever and the back up your home directory as usual.

**Comment by Syzygianinfern0** [comment]
Thanks!
