### ISSUE TITLE
Considerable freeze/hang in Gnome after copying or selecting something from history

### ISSUE THREAD

**Issue by Naahuel** [Tudmotu/gnome-shell-extension-clipboard-indicator#162]
My system:
```
OS: Pop!_OS 19.04 x86_64 
Host: 81FV Lenovo Legion Y530-15ICH 
Kernel: 5.0.0-21-generic 
DE: GNOME 3.32.1 
WM: GNOME Shell 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: NVIDIA GeForce GTX 1050 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 4870MiB / 7847MiB 
```
This isn't a particularly slow computer, **but** I do have a mechanical hard drive which is super slow. I'll admit that this freezing issue is not unique to this extension but also on other simple tasks that for some reason read or write on the disk enough to hang Gnome for a bit. However I do think that this shouldn't happen if I have the option "cache only favorites" on.

Every time I copy something to the clipboard, gnome hangs completely for a second (cursor, video, everything). I know it's because of this extension because when I disable it, this doesn't happen.

It also happens when I select something from the history.

I'm guessing the extension writes whatever I copy to disk, which causes my Gnome to crash. This shouldn't happen if I disable cache. Or even at all since I don't see how writing a small file to disk can have such a big impact on a slow disk, so maybe it's not done in an efficient way?

Thanks!

**Comment by RussianNeuroMancer** [comment]
I also can reproduce this issue on Ubuntu 19.10 with Gnome Shell 3.32.2.
