### ISSUE TITLE
GNOME 3.34 support, please!

### ISSUE THREAD

**Issue by Kerrung** [Tudmotu/gnome-shell-extension-clipboard-indicator#166]
GNOME 3.34 support, please!

**Comment by Tudmotu** [comment]
Is something not working for you? If so, please open a new issue with a proper description.

**Comment by Kerrung** [comment]
> Is something not working for you? If so, please open a new issue with a proper description.

But only for GNOME 3.26 version available.

![Screenshot from 2019-10-09 23-28-02](https://user-images.githubusercontent.com/36989404/66509544-ba486980-eaec-11e9-922e-07e939332b29.png)
