### ISSUE TITLE
How it synchronizes between computers?

### ISSUE THREAD

**Issue by leekeifuture** [Tudmotu/gnome-shell-extension-clipboard-indicator#167]
Today I cloned my HDD to another HDD and now the extension (Clipboard Indicator) exchanges everything copied between two identical hard drives, although in second HDD I left from all accounts, through which this extension can synchronize?

**Comment by Tudmotu** [comment]
I apologize, but I do not understand your issue. This extension saves a file in your home directory and that's where it keeps the history of you clipboard.
If you have anymore questions, please describe your issue more precisely.
