### ISSUE TITLE
[Feature Request] Keyboard Shortcut Key to Toggle Private Mode

### ISSUE THREAD

**Issue by blueorignal** [Tudmotu/gnome-shell-extension-clipboard-indicator#176]
Hi,

Firstly, thank you for a fantastic extension. I use it every day and it has been a life saver.

One thing which would help greatly is the ability to toggle Private Mode using a keyboard shortcut.

The use case would be for example as you go to log into a web-site and copy a password from your password manager it would be great to quickly toggle Private Mode on, enter password, and then toggle Private Mode back off.

Currently I do this with the menu item, but a keyboard shortcut would save time for an action that I preform many times a day.

Thanks again for the great work.

**Comment by fourstepper** [comment]
Yes!

**Comment by blueorignal** [comment]
@Tudmotu, is there anything I can do to assist getting this feature implemented?

The addition of a shortcut key would require almost no new code:

1) Add additional short-cut key "Toggle Private Mode" to menu in addition to existing shortcut keys.
2) Link new "Toggle Private Mode" shortcut key to existing code for "Private Mode" menu toggle.

In summary, the new "Toggle Private Mode" shortcut key would point to the same code that already exists fort the current "Private Mode" toggle. The only difference is that now you would be able to activate "Toggle Private Mode" with a keyboard shortcut.

As noted, please let me know if there is anything specific I can assist with in order to help get this change implemented.

Thanks again for a great extension.

**Comment by bjohas** [comment]
That would be great!

It would also be nice if the 'private mode state' could become a proper option, accessible from gnome-settings. As far as I can see, then state is maintained elsewhere at the moment (don't know where).

**Comment by schlagmichdoch** [comment]
This would be really great!

I'd like to automate private mode as soon as the KeePass window is focused otherwise all passwords I copy are pushed to Clipboard Inficator. Having a shortcut would make this much easier!

**Comment by Tudmotu** [comment]
I will take a look and try to get it into the GNOME 45 version.
