### ISSUE TITLE
Some translation strings are not translated in app UI

### ISSUE THREAD

**Issue by Etamuk** [Tudmotu/gnome-shell-extension-clipboard-indicator#178]
Hello,

I worked on the german translation file and with the last update you merged it into master. Thanks. 
But some strings are still not translated. Please see my screenshots with the highlighted points. 
Can you please check this? 
Thank you.

**Settings window:**
![Bildschirmfoto von 2019-10-10 19-57-36](https://user-images.githubusercontent.com/20098065/66594383-58920900-eb99-11e9-85f2-8e7b760eacc3.png)

**Indicator menu:**
![Bildschirmfoto von 2019-10-10 20-00-39](https://user-images.githubusercontent.com/20098065/66594387-5c259000-eb99-11e9-878e-5d400bcfbde2.png)

**Comment by Tudmotu** [comment]
Hi :)
Those strings were not translated. I now updated all the .po files to contain placeholders for missing strings, take a look at the de file now:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/locale/de/LC_MESSAGES/clipboard-indicator.po

You can translate the strings where the translation is empty. Would be appreciated :)

**Comment by Etamuk** [comment]
Hello :-) 

Thank you very much for updating this. That's nice :-) 
So I finished german translation yet.

**Comment by rouelle** [comment]
The same strings where not translated in french too!
Also, please, change
clipboard-indicator@tudmotu.com/locale/fr_FR to clipboard-indicator@tudmotu.com/locale/fr
so that every french locale variant works (mine is fr_CA).
Thank you for this nice extension!
[Arch Linux - Gnome 3.34]
