### ISSUE TITLE
Incompatible with some terminal emulators such as Alacritty and Kitty.

### ISSUE THREAD

**Issue by kevinhwang91** [Tudmotu/gnome-shell-extension-clipboard-indicator#181]
I'm using Alacritty which can't paste the historical content of Clipboard Indicator. and report an issue to alacritty.https://github.com/jwilm/alacritty/issues/2825

It seems that it is the problem of Clipboard Indicator. After updating the code of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/commit/4470511e61335059cc516923e7fce4afea0c1126, It works fine until e01597c327fb9842ef3cd689da0df4fd0fbc8e33.

I presume using Gtk.Clipboard of St.Clipboard makes the Alacritty work fine. I wonder why to revert the patch of  " Gtk.Clipboard instead of St.Clipboard" and find https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/177.

In my Environment(Manjaro Gnome X11), There is nothing bug happening for patching the code "Gtk.Clipboard instead of St.Clipboard".

**Comment by Tudmotu** [comment]
`Gtk.Clipboard` is not supported on Wayland, and will be replaced (it's already partially replaced) with a Mutter API called Selection API. Don't know if `Gtk.Clipboard` will be re-implemented in the future, but for now it can't be supported. Sorry :/
