### ISSUE TITLE
[Feature Request] Allow permanent entries in dropdown list

### ISSUE THREAD

**Issue by pinnerup** [Tudmotu/gnome-shell-extension-clipboard-indicator#183]
Hi there

Congrats on making such an awesome extension, that I use many times a day. Very well done!

I'd like to suggest that you perhaps add a feature, that'll allow the user to set up "permanent entries" that stay in the dropdown menu (or, perhaps, in an an expandable side menu) always, and doesn't get cycled out with new copy-actions as do regular entries.

Background:
I have a number of characters and sequences that I use almost daily but which I cannot type on my keyboard (like sequences of small caps etc.). I used to have them stored in a separate text document that I'd keep open when needed, but now they're mostly in the buffer of Clipboard Indicator. However, on a day with a lot of copying, they can get cycled out or if I increase the buffer size, be hard to find. For uses such as these, it would be nice with a category of permanent clippings in the dropdown menu.

Best regards,
Rasmus

**Comment by Tudmotu** [comment]
Is this something different than the favorites? If you click on the stars these entries will be added to the favorites and they will not be cycled.

**Comment by pinnerup** [comment]
Ah, no, that is exactly it! Thank you very much. For some reason I hadn't noticed the favourite function. Thanks again. Yours is a very useful extension, and it just got even better :)
