### ISSUE TITLE
[New translation] Add Basque localization

### ISSUE THREAD

**Issue by ibaios** [Tudmotu/gnome-shell-extension-clipboard-indicator#199]
I include here the Basque localization po file. Please include it in the project.
Thank you!
[eu.zip](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/files/4366589/eu.zip)

**Comment by Tudmotu** [comment]
Hi :) 
Thank you for taking the time to translate this extension!
Could you possibly send this as a PR?
Thanks!

**Comment by ibaios** [comment]
Hi! I have sent the PR. It's the first time I've done it, so I don't know if I did well. Please tell me if there is any problem.
