### ISSUE TITLE
Not able to open settings from menu in 3.36.1

### ISSUE THREAD

**Issue by rmader** [Tudmotu/gnome-shell-extension-clipboard-indicator#202]
This is due to a upstream change around the new extension app. We plan to add a new convenience function for that (it's already possible but a bit cumbersome).

Edit: see https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163

**Comment by memeplex** [comment]
I'm seeing this too, and it's also happening in other extensions.

**Comment by memeplex** [comment]
Thanks!
