### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by jackhill** [Tudmotu/gnome-shell-extension-clipboard-indicator#204]
Hi,

I'm interested in packaging this extension for [GNU Guix](https://guix.gnu.org). We tend to preffer released version of code, rather than just pulling from the latest git commit. I notice that the [v30](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v30) is from December or 2017. Is is possible to make a new release? It looks like a lot of good changes have been made since then.

Thanks,
Jack

**Comment by Tudmotu** [comment]
Here you go:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v34

I just uploaded it to ego so it's not live yet. Not sure if packaging from github directly is the best. If you didn't consider it yet, I think packaging the latest version from ego (extensions.gnome.org) is better.

**Comment by jackhill** [comment]
@Tudmotu thanks! Clipboard Indicator is now [packaged for Guix](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=0e741a89757537a71a6f7fb0c8e3719657cd5776). I fetched the code from GtiHub like we've done for serveral other GNOME extensions.

**Comment by jackhill** [comment]
I mean to also say, thanks for working on Cipboard Indicator. It fills a need I had beatifully!

**Comment by Tudmotu** [comment]
Thanks 😊 Glad you find it useful!
