### ISSUE TITLE
[Feature Request] Ability to Change Keyboard Shortcuts

### ISSUE THREAD

**Issue by moore-bryan** [Tudmotu/gnome-shell-extension-clipboard-indicator#205]
Not for nothing, but it'd be nice if one could change the keyboard shortcuts...

**Comment by p91paul** [comment]
You can from extension preferences. They look like labels, but you can change them by clicking on them.

**Comment by moore-bryan** [comment]
Thanks, @p91paul, I just double-clicked it and _now_ it works, but it didn't before; I wonder if something form the Solus repos updated...

**Comment by GabrielPavel** [comment]
Hello, for me this doesn't work. Ubuntu 18.04 with Gnome

**Comment by GabrielPavel** [comment]
ok, for anyone that come here with the same issue, it does work, but only after restarting shell ((Alt+F2 and  'r' in the prompt) and clicking **exactly** on the shortcut (so where CRTL+Fx is written, not anywhere else on that line)

**Comment by maurerle** [comment]
Maybe this should be reopened as a feature-request to allow setting a different shortcut by clicking anywhere in the line?
I had to search and come here to find what I was doing wrong too
