### ISSUE TITLE
need to click two times on clip to be able to paste it. 

### ISSUE THREAD

**Issue by tuxedotje** [Tudmotu/gnome-shell-extension-clipboard-indicator#209]
need to click two times on clip to be able to paste it. 
Fedora 31

**Comment by elpraga** [comment]
Yes, I am having the same issue on Ubuntu 20.04 Gnome 3.36 running on Wayland.

Any ideas why that might be happening and how to fix that?

**Comment by elpraga** [comment]
Seems to be a duplicate of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/198

**Comment by elpraga** [comment]
Seems to be fixed now in Ubuntu 20.04

**Comment by Tudmotu** [comment]
Closing, see discussing in #198. You can thank @rmader :)
