### ISSUE TITLE
Selecting an old clipping from the list does not update the preview in the top bar

### ISSUE THREAD

**Issue by elpraga** [Tudmotu/gnome-shell-extension-clipboard-indicator#210]
When I copy a new clipping using Control+C, the preview text in to top bar gets updated accordingly. 

Nevertheless, if I select an old clipping from the list, I can paste it, but the preview text in top bar does not reflect the change.

**Comment by Tudmotu** [comment]
Interesting, thanks for reporting!
Unfortunately I don't have much time to work on this extension, so I'm not sure when will that be fixed. Bug again, thank you for reporting and hopefully I will get to it somewhen :)
