### ISSUE TITLE
Refactoring translations 

### ISSUE THREAD

**Issue by b00f** [Tudmotu/gnome-shell-extension-clipboard-indicator#212]
For managing translations more efficient we can:
- Remove line Numbers from po files
- Sort translations, which help to not get huge diff for changing text position  
- Removing compile file (mo file)
- Creating a makefile target for updating po files

**Comment by Tudmotu** [comment]
1. If we don't include the .mo files, translations will not work out-of-the-box, right?
2. About a makefile - We currently have several scripts in the repo for bundling the zip file, compiling translations and updating the po files. Not sure we need a make file, but if you like you can combine these scripts into a single makefile and open a PR for that change.

**Comment by RaphaelRochet** [comment]
Oh please don't add additional steps that will prevent cloning in gnome-shell/extensions folder !
A simple bash script to update po files from pot, and recompile all mo files if you want, but please no makefile ....

**Comment by b00f** [comment]
@Tudmotu We can compile mo files from po file before making a bundle. I think the best place is `bundle.sh`
@RaphaelRochet You have a point. As I can see most of developers are working in `gnome-shell/extensions` folder. Which I believe it is not a good practice. But it is so common. There is no need for Makefile right now. 

Maybe we can discuss about keeping mo files inside the repo or just generate them from po files.

The real pain is for any simple change in the code, we have huge diffs in translations. which we need to prevent it. Removing line numbers, sorting translations will address this issue.
