### ISSUE TITLE
Feature: Search function

### ISSUE THREAD

**Issue by jusa213** [Tudmotu/gnome-shell-extension-clipboard-indicator#22]
Hello

Would it be possible to have a search function integrated into the extension? Would be a nice thing if there is a huge amount of data kept in the history.

Thx for considering.

**Comment by Tudmotu** [comment]
This sounds like a nice feature to have. :)
Thanks, I'll think about how to implement this.

**Comment by douglasduteil** [comment]
Sorry to re-up but I'm interested in this feature :lollipop: 
Did you have the time to start something @Tudmotu ?

#FirstGnomeExtensionContribution
Can you help me figuring out how to contribute to your extension ?
I have an implementation idea but I don't know how to test it...


Thanks for this extremely useful extension :+1: 

PS: I'm running Gnome 3.22 on Arch

**Comment by Tudmotu** [comment]
Hi there @douglasduteil!
To contribute to the extension, you need to create a fork for the project, and clone the repository as explained in the readme file.
Once you have the source code on your system, you will be able to modify it and see the changes on your system. You need to reload the extension after you change code, you can use https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/ for that purpose.

Please let me know if you need any further help with that. :smiley:

**Comment by douglasduteil** [comment]
Wow cool thanks a lot @Tudmotu.
This gnome-shell-extension-reloader is what I've been missing.
It was a pain to logout/login after each changes... :+1:

**Comment by Tudmotu** [comment]
This has been implemented in #90
