### ISSUE TITLE
Favorites or Pinned

### ISSUE THREAD

**Issue by b00f** [Tudmotu/gnome-shell-extension-clipboard-indicator#220]
I think favorite for clipboard is not a good name. We can use "Pinned" term and merge two scroll-view into the one. It has some advantages:
- Having one list is easier to implement and debug.
- More space to show item. One separator will be removed.

**Comment by RaphaelRochet** [comment]
Maybe favs and/or history (maybe keep only few last used always visible) could be changed into expandable sections that can be opened/closed ?

**Comment by Tudmotu** [comment]
1. There are two lists because the favorites should always be visible. Is it possible to accomplish with a single list?
2. Separator is there on purpose, should stay.
3. I like the "Pinned" terminology, we can possibly do that part, but I feel there are more important issues to work on

**Comment by b00f** [comment]
> Maybe favs and/or history (maybe keep only few last used always visible) could be changed into expandable sections that can be opened/closed ?

We can merging this two sections (fav/history) into one. In this case favs (or pinned) are always at the top of the list.

**Comment by b00f** [comment]
> There are two lists because the favorites should always be visible. Is it possible to accomplish with a single list?

Yes, We can have only one list, that the pinned items are always at the top of the list. They are pined and not movable.
 
> Separator is there on purpose, should stay.

What is the purpose behind that? Removing the separator would give more space for showing items.
