### ISSUE TITLE
Support paste-on-click

### ISSUE THREAD

**Issue by SUPERCILEX** [Tudmotu/gnome-shell-extension-clipboard-indicator#224]
When going through the clipboard history, it would be nice if clicking an old item automatically pasted its contents instead of having to click and then paste.

**Comment by salim-b** [comment]
Yeah, but please make this feature optional! I like the current behaviour.

**Comment by mkay581** [comment]
Yeah, Jumpcut had this feature and I loved it.

**Comment by clappis** [comment]
This feature will be great. ++

**Comment by SUPERCILEX** [comment]
Closing as duplicate of #109
