### ISSUE TITLE
Random history loss on GS restart

### ISSUE THREAD

**Issue by somepaulo** [Tudmotu/gnome-shell-extension-clipboard-indicator#229]
Sometimes, more often than not, when Gnome Shell (3.36.2 on Arch with X11) restarts or when some other extension gets updated, most or all history is lost. This doesn't happen every time, nor does it happen with the same extension update. One time an extension gets updated with no issues, and another time that same extension updates causing history loss in Clipboard Indicator. Sometimes even switching an already installed and up to date extension on or off causes history loss.

The only consistency I noticed with this is that when I have over 10 items in history (approximately), the oldest three of them remain. If I have less, all the history gets wiped out.

Haven't tried this under Wayland, so don't know if it's X11 related or not.

In my use case, I keep some strings of text, special characters and URLs in history, which I don't need very often, but it saves me lots of time when I do. So these history losses are a PITA.

Whatever the cause, maybe there should be some sort of backup mechanism to enable users to restore history if need be?

**Comment by somepaulo** [comment]
Another extension update, another history loss. Not even with a GS restart.

**Comment by dirusulixes** [comment]
It happened to me too under Wayland.

**Comment by SUPERCILEX** [comment]
I believe this might be due to https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/691cf1c09dc3c7e05d4ed99e03435d25efb9f278/utils.js#L84-L90

Can you check to see if you have two files in `~/.cache/clipboard-indicator@tudmotu.com`?
