### ISSUE TITLE
History duplicates

### ISSUE THREAD

**Issue by devianpctek** [Tudmotu/gnome-shell-extension-clipboard-indicator#23]
When I log in to my session, the extension duplicates the entries that were left in previous session, but is not only one duplicate, it duplicates many times

**Comment by Tudmotu** [comment]
Ummm... Sounds weird. Can you give me more details on your system - OS and Gnome version?
Also, do you log-out/log-in or like a restart?

**Comment by devianpctek** [comment]
Hi, yes I'm using Debian stretch amd64, Gnome 3.16.2, Is not always, I just did a couple tests right now, I cleared history, then copy some text, when I logged out, I checked and there were 2 entries, one was one of the entries before I cleared the history, when I restarted there were still both entries, but I've noticed sometimes the history has 15 entries (the size set in settings) but most of them are duplicates.

**Comment by devianpctek** [comment]
Still happening, the first two entries I copied after I turned on my PC, the others were before restarting the PC and as you can see on the screenshot, they got duplicated
![clip](https://cloud.githubusercontent.com/assets/1848859/12398678/c58dccb0-bdda-11e5-935c-96c98d27e608.jpg)

**Comment by Tudmotu** [comment]
Closing this. If anyone still has issues please open a new ticket.
