### ISSUE TITLE
Gnome 3.18

### ISSUE THREAD

**Issue by MarPiRK** [Tudmotu/gnome-shell-extension-clipboard-indicator#24]
It'd be nice to add support for new Gnome 3.18 found in Fedora 23 Beta.

**Comment by ElectricPrism** [comment]
I also heavily use this extension on at least 4 Arch PCs, thank you Tudmotu for your work - we would appreciate to continue using this on 3.18. This extension is so good it should be mainlined into Gnome.

**Comment by MarPiRK** [comment]
I agree
9 paź 2015 21:54 "ElectricPrism" <notifications@github.com> napisał(a):

**Comment by Tudmotu** [comment]
Uploaded to e.g.o

**Comment by ElectricPrism** [comment]
It seems Tudmotu has already added 3.18 support but hasn't released to extensions.gnome.org

Try this

```
# Go Home
cd ~/

# Glone the Repo
git clone https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git

# Move into Gnome Extensions
mv ~/gnome-shell-extension-clipboard-indicator ~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/

# Confirm 3.18 is listed in the Meta Data
gedit ~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json

# Save, Close, and Reboot Gnome Shell by Logging Out and In
```

**Comment by Tudmotu** [comment]
Hi @ElectricPrism, I just did that now :)

**Comment by ElectricPrism** [comment]
@Tudmotu You're fast, thanks a lot for a great extension bro, much appreciated :+1:

**Comment by Tudmotu** [comment]
No problem! Thank you for using it and contributing! :)
