### ISSUE TITLE
Extension stopped working in Ubuntu 20.04 after update (of extension).

### ISSUE THREAD

**Issue by cdysthe** [Tudmotu/gnome-shell-extension-clipboard-indicator#241]
Hi,

After an extension update yesterday the extension doesn't work and it just says "Error" and it can't be activated. Settings comes up without problems. This is an extension I rely on for work so I am hoping I can get this fixed when I understand what's wrong.

**Comment by Tudmotu** [comment]
I have disabled the latest version, please downgrade to the previous one for now :)

**Comment by cdysthe** [comment]
Whew, thanks! And all my favorites are still there! :)

**Comment by alephnull** [comment]
This appears to be the error:

```
-- Logs begin at Sat 2019-08-10 11:04:30 IST, end at Wed 2020-09-30 21:43:15 IST. --
Sep 30 21:37:18 gauss gnome-shell[594724]: JS ERROR: TypeError: meta is null
                                           _patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13
                                           _patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18
                                           _buildMenu/<@/home/alok/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:133:35
                                           readRegistry/</<@/home/alok/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/utils.js:127:25
Sep 30 21:37:18 gauss gnome-shell[594724]: Usage of object.actor is deprecated for ClipboardIndicator
                                           get@resource:///org/gnome/shell/ui/environment.js:314:29
                                           _init@/home/alok/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:88:9
                                           wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                           enable@/home/alok/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:860:26
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
% gnome-shell --version
GNOME Shell 3.38.0
```

The deprecation warning might not be related to this problem.

**Comment by Tudmotu** [comment]
Thank you @alephnull !
Is this on GNOME 3.38?

**Comment by alephnull** [comment]
> Is this on GNOME 3.38?
Yes on Ubuntu Gorilla. Debian sid seems fine for the moment.

**Comment by jubnzv** [comment]
I just fixed a [similar problem](https://github.com/cinatic/taskwhisperer/issues/77) in the another extension. It seems, that replacement of `add` methods to `add_actor` will fix it. Here is [another example](https://github.com/ethanwharris/gnome-nvidia-extension/commit/cde0637eaf72d97461f96e0098149fd141d0b80b).

**Comment by fastcat** [comment]
> Debian sid seems fine for the moment

sid/bullseye now have 3.38 too, and so this issue and #242 now affects there too

**Comment by Tudmotu** [comment]
Do you see this error in Wayland or X11?

**Comment by tenfourty** [comment]
I have this issue if F33 beta on X11.

**Comment by alephnull** [comment]
As others have reported, installing the extension from master HEAD resolves the problem.

**Comment by bulletmark** [comment]
This extension installed from https://extensions.gnome.org/ does not work on stock Arch Linux since GNOME updated to 3.38. I am using Wayland.
