### ISSUE TITLE
Panel not opening in GNOME 3.38

### ISSUE THREAD

**Issue by gferon** [Tudmotu/gnome-shell-extension-clipboard-indicator#242]
I've been a faithful user of your awesome extension for a while now, and just upgraded to Fedora 33 Beta.

I tried using `lg` but the extension doesn't emit any errors when clicking on the button.

**Comment by alephnull** [comment]
Related to #241

**Comment by gferon** [comment]
> Related to #241

I also had a look at this issue, and I tried to load both [v30](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v30) and [v34](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v34) but no luck.

**Comment by gferon** [comment]
I just updated to the latest revision in `master` and it works perfectly fine! I guess a new version/tag should be published.
