### ISSUE TITLE
[Feature request] Copying string that is on the history list should move the row to 1st (top) position

### ISSUE THREAD

**Issue by kpalczewski** [Tudmotu/gnome-shell-extension-clipboard-indicator#244]
I often thought that clipboard indicator doesn't work properly and it doesn't register that I have copied something.

It turned out that I am copying the same thing as before and that string in on history list.
Clipboard indicator doesn't move the string to top and just shows a dot next to the apropriate row.

It would be awesome, if such string would be moved to the top position on history list.

**Comment by Tudmotu** [comment]
hi @kpalczewski :)
There's an option like this in the settings.

**Comment by kpalczewski** [comment]
there is!
thank you! @Tudmotu
