### ISSUE TITLE
Not working with Gnome 3.38

### ISSUE THREAD

**Issue by skewty** [Tudmotu/gnome-shell-extension-clipboard-indicator#247]
Not working with Gnome 3.38 on Ubuntu 20.10

**Comment by skewty** [comment]
Looks to be the same issue as #241

**Comment by skewty** [comment]
I see in https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/commit/afdf7fef3bd6b61f5787e93b6562fb8b608dd082 this is resolved but I do not see any new Releases or Tags.

Has this update been published to extensions.gnome.org?  If not, is there something holding it up?

**Comment by densyy** [comment]
The "Clear History" button does nothing.
It stopped cleaning.
Please fix it ;)

Hardware Info
--------
OS: Manjaro Linux x86_64
Kernel: 5.8.15-1-MANJARO
DE: GNOME 3.38.1
CPU: Intel i5-6200U (4) @ 2.800GHz
GPU: Intel Skylake GT2 [HD Graphics 520]
Memory: 7781MiB

**Comment by BenjiSan** [comment]
> The "Clear History" button does nothing.
> It stopped cleaning.
> Please fix it ;)
> 
> ## Hardware Info
> OS: Manjaro Linux x86_64
> Kernel: 5.8.15-1-MANJARO
> DE: GNOME 3.38.1
> CPU: Intel i5-6200U (4) @ 2.800GHz
> GPU: Intel Skylake GT2 [HD Graphics 520]
> Memory: 7781MiB

I had the same issue. The "clean history" doesn't work. I use Ubuntu 20.10 qith gnome 3.38

**Comment by bulletmark** [comment]
Version that works with GNOME 3.38 is released on extensions.gnome.org now.

Note it does not update cleanly, and just presents a red error button with a message "Error: A different version was loaded previously. You need to log out for changes to take effect." in my journal. Restarting chromium made no different. I had to reboot then it worked.

**Comment by Tudmotu** [comment]
As @bulletmark said, the latest version should support 3.38. Not sure about the error, though.
