### ISSUE TITLE
Move focus together with keyboard navigation ↓/↑

### ISSUE THREAD

**Issue by salim-b** [Tudmotu/gnome-shell-extension-clipboard-indicator#248]
I am unsure about the correct terminology to describe this issue.

The problem is: When I open Clipboard Indicator using the shortcut (<kbd>Super</kbd>+<kbd>C</kbd>) and then scroll down (or up) the clipboard history using <kbd>↓</kbd> (or <kbd>↑</kbd> respectively), the focus of the history doesn't follow, i.e. the visible subset of all entries doesn't change. I have to switch to the mouse/touchpad instead to being able to "visually" scroll.

Here's a GIF that might better show what I mean:

![Peek 2020-10-17 23-39](https://user-images.githubusercontent.com/20040931/96354147-cdf4bb80-10c2-11eb-8b27-18a0030612b4.gif)

**Comment by SUPERCILEX** [comment]
Fixed in https://github.com/SUPERCILEX/gnome-clipboard-history/issues/32
