### ISSUE TITLE
Unable to clear all history when built from master

### ISSUE THREAD

**Issue by mcl21014** [Tudmotu/gnome-shell-extension-clipboard-indicator#250]
OS: Ubuntu 20.10 amd64
I've tried cloning from master and compiling the extension manually, and everything works except clearing all history. Individual items can still be cleared, though. Thank you for fixing the other issues upstream, though. It will launch on GNOME 3.38. And that's the only thing I know of that doesn't work anymore.

**Comment by Tudmotu** [comment]
Fixed by @l3nn4rt in #249 :)
