### ISSUE TITLE
Can you create a GitHub tag for the version 36 release?

### ISSUE THREAD

**Issue by jonafato** [Tudmotu/gnome-shell-extension-clipboard-indicator#253]
Version 36 is published to EGO but not tagged on GitHub. I'd like to update the [package for NixOS](https://github.com/NixOS/nixpkgs/blob/ceb1527a6192764651929f97a7f502a08a496b49/pkgs/desktops/gnome-3/extensions/clipboard-indicator/default.nix), which currently points to the version 34 tag.

Thanks for making clipboard indicator, it's one of my favorite gnome extensions!

**Comment by Tudmotu** [comment]
I was waiting for v37 to be approved since it contains the fix for the "clear history" button :)
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/v37

**Comment by jonafato** [comment]
Awesome, thank you!
