### ISSUE TITLE
Does not work on Gnome 3.38.1 (Ubuntu 20.10)

### ISSUE THREAD

**Issue by str** [Tudmotu/gnome-shell-extension-clipboard-indicator#256]
Creat project, congrats. It's one of my critical apps.  

It stopped working after the ubuntu 20.10 upgrade :(

**Comment by Tudmotu** [comment]
Hi,
Can you try to logout and log in again and see if it helps?

**Comment by str** [comment]
I already tried, rebooting, uninstalling and installing it again without success

**Comment by LordChaos73** [comment]
Works fine on my machine...Ubuntu 20.10 as well. Did you remove the following directories before re-installing?

`~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com`
`~/.cache/clipboard-indicator@tudmotu.com/registry.txt`

**Comment by str** [comment]
It seems to work with the latest update. THANK YOU
