### ISSUE TITLE
possibility of redacting passwords from password managers

### ISSUE THREAD

**Issue by NotAFile** [Tudmotu/gnome-shell-extension-clipboard-indicator#265]
I'm not sure how possible this is given the implementation, but it would be useful to be able to copy things from my password manager without them showing up or staying in the clipboard history.

Could this be implemented as an application blacklist? Or would further metadata e.g. from the application be needed?

**Comment by dehoej** [comment]
I am using clipboard indicator but feel a little bad about it since my passwords are lying around in the clipboard. In this world of password managers this needs to be addressed. Can we come up with an idea of how to solve this?

**Comment by Tudmotu** [comment]
We tried many times to come up with something, but due to the limitations of being a GNOME extensions (versus an actual app) this seems impossible.

If anyone ever comes up with a viable idea how to implement this I will gladly support them.

Closing this issue for now.
