### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by frandieguez** [Tudmotu/gnome-shell-extension-clipboard-indicator#272]
**Extension Information**

* Shell Version: GNOME 40
* Extension Version: 37
* Install method: extension.gnome.org
* OS: Fedora 33 with GNOME 40 alfa installed `sudo dnf copr enable haeckerfelix/gnome-shell-40 &&  sudo dnf update`

**Describe the bug**
GNOME 40 is already in alfa and it forces the usage of GTK4 for extensions dialogs.

This extensions works pretty well until you open the prefences panel with the next output:

```
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  _init@/home/fran/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:50:21
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/fran/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:247:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Please consider update to GTK4, to keep this awesome extension usable

**Comment by Tudmotu** [comment]
Is GNOME 40 released already?
Are there going to be breaking changes with GTK4? If so, I would assume a lot of extensions are going to break...

**Comment by frandieguez** [comment]
hi, GNOME 40 stable is not released yet, they have published an alpha version, that they are now asking for testers.
One of the main changes for extensións is that now the preferences dialog must be in gtk4, potentially affecting a lot of extensions. 
I've just open this bug report to inform you about the changes before stable release is published.

With gnome boxes is quite easy to test it

**Comment by Tudmotu** [comment]
Ok, got it. Thanks 🙂

**Comment by 5n00p4eg** [comment]
Just upgraded to Fedora 34 Beta with Gnome 40, waiting for a new version as well!! Thanks, guys for contributing, it is a very useful plugin!

**Comment by fastrizwaan** [comment]
@Tudmotu Bro, just installed fedora 34 beta, it's pretty stable. Clipboard Indicator is one of the 3 most important extension I use. Kindly support Gnome 40.0. Thanks!

**Comment by DerRoger** [comment]
@Tudmotu, just to add to this: Gnome 40 stable has been officially released now, so you won't risk having to redo your changes. Any changes you make are for the offical, stable Gnome 40.

**Comment by sallyahaj** [comment]
Just upgrade to Fedora 34 beta, hope we can see the extension soon on the new Gnome 40.

**Comment by HougeLangley** [comment]
https://www.omgubuntu.co.uk/2021/03/gnome-40-official-release

![image](https://user-images.githubusercontent.com/1161594/113158226-2fbe7180-926e-11eb-9595-82e20906b9fa.png)

OK, @Tudmotu please upgrade

**Comment by StripedMonkey** [comment]
Gnome 40 is the current version of gnome shell on Arch, so this is likely going to get many more requests for this to get updated soon.

**Comment by HougeLangley** [comment]
You guys could do not using this one, try gpaste.

Working great

**Comment by MrTomRod** [comment]
[This fork](https://github.com/RuiGuilherme/gnome-shell-extension-clipboard-indicator) supports Gnome 40.

**Comment by Kerrung** [comment]
The extension doesn't work on Arch Linux GNOME 40 even after today's update. Log is here:

The settings of extension clipboard-indicator@tudmotu.com had an error:
```
Error: No property margin on GtkGrid
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
_init@/home/user/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:50:21
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:247:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

![Screenshot from 2021-04-16 23-51-34](https://user-images.githubusercontent.com/36989404/115071001-1cb6cd00-9f0f-11eb-8524-5164063c629a.png)

**Comment by amiga23** [comment]
Works fine on latest Manjaro, just the settings do not work:
```
Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
  _init@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:22
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
  buildPrefsWidget@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by MrTomRod** [comment]
I still cannot install any version on Fedora 34, Gnome 40.1.0.
