### ISSUE TITLE
[Feature Request] Add clear clipboard option

### ISSUE THREAD

**Issue by developomp** [Tudmotu/gnome-shell-extension-clipboard-indicator#278]
Our passwords can get vulnerable while copying passwords, so a button to clear what's currently in the clipboard would be very helpful.
Also, just in case someone might ask this, clearing the clipboard history doesn't touch what's currently in your clipboard.

**Comment by developomp** [comment]
@Tudmotu is the feature implemented somewhere?

**Comment by Tudmotu** [comment]
Yes, an option was added to the settings in the latest version:
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/506487/8e66a3dd-349b-43a6-9728-6f43f0b61473)
