### ISSUE TITLE
Replace confirmation+popup UI by a notification with cancel action

### ISSUE THREAD

**Issue by RaphaelRochet** [Tudmotu/gnome-shell-extension-clipboard-indicator#28]
This would integrate better with GNOME Shell way. Also less mouse moves/clicks.

Look at what happens when you add or remove a favorite application in the Shell dock to see it in action.

**Comment by bil-elmoussaoui** [comment]
I replaced the old notification on #33 , but i don't know how to add action buttons to the notification on GJS. Do you know if an extension uses it ?

**Comment by RaphaelRochet** [comment]
Yeah, ... mine do it ;)
https://github.com/RaphaelRochet/arch-update

Really easy in fact :
```
notification.addAction( _('Update now') , Lang.bind(this, function() {this._updateNow()}) );
```

**Comment by bil-elmoussaoui** [comment]
Thanks! i will take a look at this later
