### ISSUE TITLE
Clear history preserves the last item copied

### ISSUE THREAD

**Issue by raffaem** [Tudmotu/gnome-shell-extension-clipboard-indicator#281]
The "clear history" menu option preserves the last element copied.

Would it be possible to remove that too?

It is very counter intuitive. 

After you click the "Clear history" button, the message box promises "to delete ***all*** clipboard items"

**Comment by mcl21014** [comment]
Can reproduce. Actually, I've known for a while. Was too lazy to report.

**Comment by sWoRm** [comment]
It seems already documented in the code:

https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L354

> // We can't actually remove all items, because the clipboard still
        // has data that will be re-captured on next refresh, so we remove
        // all except the currently selected item

**Comment by Tudmotu** [comment]
I think this can be mimicked by setting the clipboard to an empty string. Marking this as "bug" and "up for grabs" in case anyone would like to pick this up.

**Comment by Suryavarman-II** [comment]
agree. it keeps the last one till the next login. what about having an option for auto-delete while log out or technically clear the history while login?

in ungoogled-chromium for example the extensions for auto-cleaning the browser history actually delete the data when you start a new session and not when you close the browser.
