### ISSUE TITLE
[Feature Request] Application Blacklist

### ISSUE THREAD

**Issue by sgmiller** [Tudmotu/gnome-shell-extension-clipboard-indicator#282]
It would be nice if I could exclude certain applications (maybe just by title) from saving in history.  In particular I'd like to avoid copies from my password manager (KeePass) from being captured for security reasons.

**Comment by jlemonde** [comment]
I'd love that feature too! I am always in the fear of forgetting to enable 'private mode' in the clipboard manager, so usually I prefer to turn off the extension altogether... Application blacklist is a must!

**Comment by Tudmotu** [comment]
Unfortunately, this is not possible.

**Comment by jlemonde** [comment]
I'm never going to use it, thus. It's just too dangerous to get a password written in clear in the extension.

**Comment by Tudmotu** [comment]
Completely agree, if you use a password manager, this extension is not for you.

I do believe some of the fancier clipboard managers have more security. The fact this is a gnome extension (and not a full app) limits its options considerably.

**Comment by ArtyIF** [comment]
Pano has an app blacklist, and it's a GNOME Extension. Why can't this one? Really, it's a "check the app the clipboard entry is from and don't add it to the list if it matches the blacklist" kinda deal, as I see it.

**Comment by Tudmotu** [comment]
@ArtyIF I will gladly review a PR if you can implement it.
Note that Pano is not a vanilla gnome extension, it requires you to install some packages as well, so not sure how they do that exactly.
