### ISSUE TITLE
Are you going to update the extension to GNOME 40 ?

### ISSUE THREAD

**Issue by KonstantMan** [Tudmotu/gnome-shell-extension-clipboard-indicator#284]

**Comment by jbodhorn** [comment]
PLS PLS PLS update! this was my favorite extension

**Comment by rhysallenuk** [comment]
Gnome 40 - Error in Extensions 

![image](https://user-images.githubusercontent.com/35865113/114160099-740cda00-991e-11eb-9647-a72a630bc704.png)

Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  _init@/home/####/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:50:21
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
  buildPrefsWidget@/home/####/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:247:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by jbodhorn** [comment]
> Gnome 40 - Error in Extensions
> 
> ![image](https://user-images.githubusercontent.com/35865113/114160099-740cda00-991e-11eb-9647-a72a630bc704.png)
> 
> Error: No property margin on GtkGrid
> 
> Stack trace:
> _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
> _init@/home/####/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:50:21
> wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
> _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
> newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
> buildPrefsWidget@/home/####/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:247:18
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> start@resource:///org/gnome/gjs/modules/script/package.js:190:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Where would I get that info from so I can post my error in case it's different?

**Comment by rhysallenuk** [comment]
Go to Extensions App, find the faulty Extension and click the Cog button.

**Comment by jbodhorn** [comment]
> Go to Extensions App, find the faulty Extension and click the Cog button.

ty

**Comment by jbodhorn** [comment]
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  _init@/home/joe/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:50:21
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
  buildPrefsWidget@/home/joe/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:247:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by oneiroi-el** [comment]
To have this extension with gnome 40 you just have to change the metadata file
/home/mael/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
and add 40 to it.
It's give you that :
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Clipboard Manager extension for Gnome-Shell - Adds a clipboard indicator to the top panel, and caches clipboard history.",
  "name": "Clipboard Indicator",
  "shell-version": [
    "40"
  ],
  "url": "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator",
  "uuid": "clipboard-indicator@tudmotu.com",
  "version": 37
}

But the settings panel doesn't work

**Comment by jbodhorn** [comment]
> To have this extension with gnome 40 you just have to change the metadata file
> /home/mael/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
> and add 40 to it.
> It's give you that :
> {
> "_generated": "Generated by SweetTooth, do not edit",
> "description": "Clipboard Manager extension for Gnome-Shell - Adds a clipboard indicator to the top panel, and caches clipboard history.",
> "name": "Clipboard Indicator",
> "shell-version": [
> "40"
> ],
> "url": "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator",
> "uuid": "[clipboard-indicator@tudmotu.com](mailto:clipboard-indicator@tudmotu.com)",
> "version": 37
> }
> 
> But the settings panel doesn't work

Damn, now I wish I hadn't uninstalled it, lost all my settings.... Now I'm gonna have to figure out what my settings were and add them manually, what a pita, just glad I can use it again atm, ain't nothing ever easy

**Comment by KonstantMan** [comment]
> > To have this extension with gnome 40 you just have to change the metadata file
> > /home/mael/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
> > and add 40 to it.
> > It's give you that :
> > {
> > "_generated": "Generated by SweetTooth, do not edit",
> > "description": "Clipboard Manager extension for Gnome-Shell - Adds a clipboard indicator to the top panel, and caches clipboard history.",
> > "name": "Clipboard Indicator",
> > "shell-version": [
> > "40"
> > ],
> > "url": "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator",
> > "uuid": "[clipboard-indicator@tudmotu.com](mailto:clipboard-indicator@tudmotu.com)",
> > "version": 37
> > }
> > But the settings panel doesn't work
> 
> Damn, now I wish I hadn't uninstalled it, lost all my settings.... Now I'm gonna have to figure out what my settings were and add them manually, what a pita, just glad I can use it again atm, ain't nothing ever easy

How did you manage to install the extension from github ? i added it to /home/username/.local/share/gnome-shell/extensions but it doesn't appear in the extensions app

**Comment by jbodhorn** [comment]
> > > To have this extension with gnome 40 you just have to change the metadata file
> > > /home/mael/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
> > > and add 40 to it.
> > > It's give you that :
> > > {
> > > "_generated": "Generated by SweetTooth, do not edit",
> > > "description": "Clipboard Manager extension for Gnome-Shell - Adds a clipboard indicator to the top panel, and caches clipboard history.",
> > > "name": "Clipboard Indicator",
> > > "shell-version": [
> > > "40"
> > > ],
> > > "url": "https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator",
> > > "uuid": "[clipboard-indicator@tudmotu.com](mailto:clipboard-indicator@tudmotu.com)",
> > > "version": 37
> > > }
> > > But the settings panel doesn't work
> > 
> > 
> > Damn, now I wish I hadn't uninstalled it, lost all my settings.... Now I'm gonna have to figure out what my settings were and add them manually, what a pita, just glad I can use it again atm, ain't nothing ever easy
> 
> How did you manage to install the extension from github ? i added it to /home/username/.local/share/gnome-shell/extensions but it doesn't appear in the extensions app

I just follow the install instructions:

Installation via git is performed by cloning the repo into your local gnome-shell extensions directory (usually ):~/.local/share/gnome-shell/extensions/

$ git clone https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git /home/joe/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com

Then I edited the metadata.json, when I edited the file I had to out just 40, not like 40.0.0 or whatever. Then I rebooted, though I think you can just log out and log back in. It wasn't working for me the first attempt bc I had put 40.0 instead of just 40. 

Now it's not working again for me, I dunno if I just need a reboot or what. I'm updating atm and if it's not working after a reboot I'm gonna try changing the number. I believe I'll have gnome-shell 40.0-1, so if it's not working hopefully I just gotta change the number

**Comment by jbodhorn** [comment]
Lol, somehow the extension got removed, guess that'd be a good reason for it to not work..... I have no idea how that happened

**Comment by SurPaul** [comment]
A new version for Gnome Shell 40 is already available there: https://extensions.gnome.org/extension/779/clipboard-indicator/. I updated, everything works. Thanks to the developers!

**Comment by Tudmotu** [comment]
Apologies for the inconvenience :) 
Glad it works now!

**Comment by Tudmotu** [comment]
BTW you can thank @justperfection who fixed it :)
