### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by jonian** [Tudmotu/gnome-shell-extension-clipboard-indicator#288]
Hi @Tudmotu, please add new releases/tags on GitHub. I maintain the AUR package https://aur.archlinux.org/packages/gnome-shell-extension-clipboard-indicator and would like to update to the GNOME Shell 40 compatible version.

Thanks!

**Comment by Tudmotu** [comment]
Apologies for the late response. Done:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v38

**Comment by jonian** [comment]
Thanks @Tudmotu!
