### ISSUE TITLE
Add a "Private mode" switch

### ISSUE THREAD

**Issue by RaphaelRochet** [Tudmotu/gnome-shell-extension-clipboard-indicator#29]
So one can temporary disable the clipboard monitor, for the same reason private mode exists on browsers ;) 
A 'disabled' (50% transparent) icon could indicate the 'off' state.

**Comment by Tudmotu** [comment]
Does middle-clicking the indicator sounds like a good interface for that? :)

**Comment by RaphaelRochet** [comment]
Having both could be handy ;)
Need help ?

**Comment by Tudmotu** [comment]
Yeah, sure! Feel free to implement this if you like! Sounds like a good feature to me. :)

**Comment by RaphaelRochet** [comment]
Ok, I'm on it.

**Comment by RaphaelRochet** [comment]
Didn't find how to implement middle-click toggle, the St.Icon widget seems to have only "popupmenu" signal.

**Comment by trusktr** [comment]
Cool. Would be nice to list what "private mode" is in the README and/or in the settings window.
