### ISSUE TITLE
Option to hide clipboard icon

### ISSUE THREAD

**Issue by Freeplayg** [Tudmotu/gnome-shell-extension-clipboard-indicator#293]
Since you can set a keybind to toggle the popup, maybe an option to hide the icon would to be nice so that it'll only be there when it's needed.

**Comment by 3m4r5** [comment]
same here, I don't need the icon

**Comment by Tudmotu** [comment]
Interesting idea :+1:

**Comment by ryleu** [comment]
Might work on this.

**Comment by Tudmotu** [comment]
Need to also think how users will access the settings if the icon is hidden.

**Comment by 3m4r5** [comment]
@Tudmotu from the gnome extensions app?

**Comment by 3m4r5** [comment]
or using the the keyboard shortcut to invoke the panel & the clicking on the settings option

**Comment by Tudmotu** [comment]
@3m4r5 ah yes, forgot about that
