### ISSUE TITLE
Pinned Clipboard Entries lost

### ISSUE THREAD

**Issue by kleinph** [Tudmotu/gnome-shell-extension-clipboard-indicator#297]
2 of my 3 pinned entries got lost somehow.

I am using version v38 under Gnome 40 in Arch Linux.

**Comment by mptpro** [comment]
It'd be great if we could export/import our pinned entries.

**Comment by Tudmotu** [comment]
@mptpro that's an interesting idea..
@kleinph Not sure I can assist since you shared no details and you opened this in May :)
I am closing but if this is still an issue, please open a new issue with more details.

**Comment by kleinph** [comment]
I am not sure which additional info I can provide. I can only say that it happened to me a few days ago again.  
Should I open a new ticket?

**Comment by Tudmotu** [comment]
Yes, please open a new issue with steps to reproduce.
And if you know your way around gnome-shell, then finding an error message in the logs can be really helpful.

But steps to reproduce could also be enough.

Thanks.
