### ISSUE TITLE
GNOME 41 compatibility

### ISSUE THREAD

**Issue by frandieguez** [Tudmotu/gnome-shell-extension-clipboard-indicator#307]
In some days GNOME 41 will be released and I have tested your extension by simply adding the new version to the `metadata.json` file.

```
    "shell-version": [
        "40",
        "41"
    ],
```

It will be awesome to have your extension compatible on day-one.

**Comment by jacksongoode** [comment]
Made a PR #309

**Comment by apinter** [comment]
Would be nice to have the PR accepted ^_^

**Comment by jacksongoode** [comment]
@Tudmotu any thoughts?

**Comment by nasimOfficial** [comment]
@Tudmotu  wake up

**Comment by m2jest1c** [comment]
where clipboard 😔

**Comment by vaslabs** [comment]
I also tested it on fedora 35, just adding the version in `.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/` everything seems in order

**Comment by Eonfge** [comment]
The maintainer is waiting for Arch to have GNOME 41:

https://extensions.gnome.org/extension/779/clipboard-indicator/

7th or so comment. Click `Show more reviews` to see his statement.

**Comment by prajwel** [comment]
> The maintainer is waiting for Arch to have GNOME 41:
> 
> https://extensions.gnome.org/extension/779/clipboard-indicator/
> 
> 7th or so comment. Click `Show more reviews` to see his statement.

I was under the impression that Arch was early to adopt new technologies? 🤨

**Comment by MaybeAdmin** [comment]
> I also tested it on fedora 35, just adding the version in `.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json` everything seems in order

this isnt working for me on arch

**Comment by bulletmark** [comment]
Arch has now been updated to GNOME 41 so can we have this extension updated please.

**Comment by MaybeAdmin** [comment]
> Arch has now been updated to GNOME 41 so can we have this extension updated please.

Haha we just have to wait for the dev

**Comment by vikas-kyatannawar** [comment]
Damn, I was so reliant on this for my daily work. Waiting eagerly for this.

**Comment by puyoxyz** [comment]
clip bord pls :3

**Comment by sith-on-mars** [comment]
I was eagerly waiting for the newer version for Gnome 41 until I found [GPaste](https://github.com/Keruspe/GPaste).

**Comment by LittleWhole** [comment]
> The maintainer is waiting for Arch to have GNOME 41:
> 
> https://extensions.gnome.org/extension/779/clipboard-indicator/
> 
> 7th or so comment. Click `Show more reviews` to see his statement.

Just got GNOME 41 on Arch a few hours ago, would be nice to get this extension upgraded!

**Comment by Tudmotu** [comment]
I'm working on it now. I've been waiting for Arch to get the 41 update.

Everyone who sent a PR adding the "41" to the metadata - I appreciate you trying to help, but FYI this is just spamming my mentions. Please don't do that. I am capable of adding the "41" to the metadata, I don't need a PR for that. There were like 6-7 people who opened a PR like that, which means you didn't even bother to look at the other PRs.

I will upload a 41 compatible version soon.

**Comment by Tudmotu** [comment]
Uploaded a new version that support GNOME 41.
Apologies for the long time it took, I was also waiting for it.... :)
