### ISSUE TITLE
I have a problem when i want to use the extension

### ISSUE THREAD

**Issue by abolfazlalz** [Tudmotu/gnome-shell-extension-clipboard-indicator#311]
Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/home/abolfazl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
  _init@/home/abolfazl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/abolfazl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by Tudmotu** [comment]
Closing in favor of #316 , looks like the same issue
