### ISSUE TITLE
clipboard indicator settings error

### ISSUE THREAD

**Issue by springfieldsmith** [Tudmotu/gnome-shell-extension-clipboard-indicator#316]
Please help. When I try to open settings it always opens a window with the following window/ error message: 
![image](https://user-images.githubusercontent.com/58962631/141417517-3cdddd66-2abd-478c-ba83-4f8038086f50.png)

Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/home/b/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
  _init@/home/b/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/b/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by HarishTeens** [comment]
I'm getting the same error. Is there any fix yet?

**Comment by Tudmotu** [comment]
Can you all please share your GNOME versions + distro?

**Comment by HarishTeens** [comment]
GNOME Shell 3.36.9
Ubuntu 20.04.3 LTS

**Comment by springfieldsmith** [comment]
GNOME Shell 3.36.8
Ubuntu 20.04.3 LTS

**Comment by Tudmotu** [comment]
Ah, ok - Please install Clipboard Indicator v37 or upgrade to GNOME 40.
v38 and above only support GNOME version >= 40 due to incompatible changes in GNOME 40.
See also:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/296

**Comment by HarishTeens** [comment]
But there was only one release package for v38. Could you provide the link for v37 please?

**Comment by springfieldsmith** [comment]
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v37

**Comment by springfieldsmith** [comment]
https://extensions.gnome.org/extension/779/clipboard-indicator/

**Comment by springfieldsmith** [comment]
> But there was only one release package for v38. Could you provide the link for v37 please?

just posted options for v37 and earlier. they were not obvious links to find it but they are still available

**Comment by Tudmotu** [comment]
Thank you @springfieldsmith 
Also I believe you can install older versions from extensions.gnome.org as well :)
