### ISSUE TITLE
Review for version v39 on e.g.o

### ISSUE THREAD

**Issue by Tudmotu** [Tudmotu/gnome-shell-extension-clipboard-indicator#318]
From @justperfection :

1. Please remove all .po and .pot files:
https://gjs.guide/extensions/review-guidelines/review-guidelines.html#don-t-include-unnecessary-files

2. Lang is a deprecated module. Please remove it for the next version:
https://gjs.guide/extensions/review-guidelines/review-guidelines.html#general-advice
Learn how to remove Lang from your code:
https://gjs.guide/guides/gjs/legacy-class-syntax.html

If you need any help with your extension you can ask us on:
GNOME Matrix channel: https://matrix.to/#/#extensions:gnome.org
IRC Bridge: irc://irc.gimpnet.org/shell-extensions

**Comment by justperfection** [comment]
For number 1, I recommend to use `gnome-extension pack` command for creating packages. It has some benefits:

- You won't have locale or schema files in your source.
- You don't need to compile schema and .po files manually.

The package `gnome-extension` command is generating can be uploaded to the ego.
You can also install that package file with `gnome-extensions install --force file.zip` during developing process.

You can use [my script](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/blob/main/scripts/build.sh) as an example.

Also add these to gitignore to avoid uploading temp and zip files to repo:

```
*~
*.zip
```

**Comment by Tudmotu** [comment]
Cool, thanks!
