### ISSUE TITLE
Cannot enter settings

### ISSUE THREAD

**Issue by gytdev** [Tudmotu/gnome-shell-extension-clipboard-indicator#324]
When pressing "Settings" on the Clipboard indicator, I get this "Something gone wrong" error:

```
Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/home/gytdev/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
  _init@/home/gytdev/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/home/gytdev/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Tudmotu** [comment]
Thanks for reporting.
Can you please share your GNOME version and the extension's version?

**Comment by kowsiknd** [comment]
I am facing the same issue. Gnome and gnome-shell version 3.36. Extension version 34

**Comment by bryandidur** [comment]
I was facing the same issue here. But, following the instructions in the [GNOME Version Support](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator#gnome-version-support) topic from the **README.rst** file and installing the _v37_ version of the extension in my GNOME 3.36.8, solves the problem.

**Comment by tomaszstachera** [comment]
> I was facing the same issue here. But, following the instructions in the [GNOME Version Support](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator#gnome-version-support) topic from the **README.rst** file and installing the _v37_ version of the extension in my GNOME 3.36.8, solves the problem.

Worked!
