### ISSUE TITLE
The settings of extension clipboard-indicator@tudmotu.com had an error

### ISSUE THREAD

**Issue by askadhum** [Tudmotu/gnome-shell-extension-clipboard-indicator#325]
```
ImportError: No JS module 'clipboard-indicator@tudmotu.com' found in search path
```

Stack trace:
```
installImporter@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:290:5
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:211:28
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Gnome version: 41.2

**Comment by Tejas20002** [comment]
The settings of extension clipboard-indicator@tudmotu.com had an error:
```
Error: Could not guess unspecified GValue type
```

Stack trace:
```
addKeybinding@/home/popeye/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
_init@/home/popeye/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
buildPrefsWidget@/home/popeye/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by lucianocavallo** [comment]
I've had the same error of Tejas20002:

Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
  _init@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
  buildPrefsWidget@/usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
