### ISSUE TITLE
[Feature Request] Paste on selection

### ISSUE THREAD

**Issue by mpetuska** [Tudmotu/gnome-shell-extension-clipboard-indicator#327]
Currently it's already possible to navigate history and change clipboard selection with just a keyboard, however after older item is selected, one must still paste it again manually. It would be great to have Windows-like behaviour where one could paste on selection as well.

## Current Behaviour
1. Setup `Super+V` shortcut to bring up clipboard history
2. Invoke `Super+V`
3. Navigate with arrow keys to select older item
4. `CTRL+V` to paste that older item
5. Item gets pasted

## Desired Behaviour
1. Setup `Super+V` shortcut to bring up clipboard history
2. [New] Toggle setting to paste on item selection
2. Invoke `Super+V`
3. Navigate with arrow keys to select older item
4. Item gets pasted

**Comment by SUPERCILEX** [comment]
Duplicate of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/109#issuecomment-1047476620
