### ISSUE TITLE
[Bug] The list doesn't scroll when I use the arrows

### ISSUE THREAD

**Issue by hyuri** [Tudmotu/gnome-shell-extension-clipboard-indicator#343]
Hi

When I use the arrows (down/up) to navigate the list, the list does not scroll down. So that means, for example, that if I press the Down key, the selection keeps going down but because the list doesn't scroll down, at some point I can't see what's selected.

**Comment by SUPERCILEX** [comment]
Duplicate of #248 and https://github.com/SUPERCILEX/gnome-clipboard-history/issues/32
