### ISSUE TITLE
Not supported on Gnome 42

### ISSUE THREAD

**Issue by LawlietRen** [Tudmotu/gnome-shell-extension-clipboard-indicator#349]
Hello, there's an error with "this.parrent", could you fix the extension so it will work with gnome 42, thanks

**Comment by pc-2198x** [comment]
`uname -a`:
`Linux GigaArch 5.17.2-zen3-1-zen #1 ZEN SMP PREEMPT Sun, 10 Apr 2022 11:18:34 +0000 x86_64 GNU/Linux`

Gnome 42.0

Extensions shows the following error message for Clipboard Indicator:
`Object 0x1a7604825a30 is not a subclass of GObject_Object, it's a Object`

**Comment by SUPERCILEX** [comment]
FYI, I've rewritten this extension (with support for Gnome 42): https://github.com/SUPERCILEX/gnome-clipboard-history

**Comment by leillo1975** [comment]
Have the same problem with Ubuntu 22.04 (Gnome Shell 42)

**Comment by pgroyal22** [comment]
> FYI, I've rewritten this extension (with support for Gnome 42): https://github.com/SUPERCILEX/gnome-clipboard-history

Have you made a PR on this project to bring it up to date?

**Comment by SUPERCILEX** [comment]
No, the new extension is supposed to supercede this one: https://github.com/SUPERCILEX/gnome-clipboard-history/issues/1#issuecomment-1042708516. I think it's fair to consider this one to be in maintenance mode.

**Comment by MaterialFuture** [comment]
PR #348 has been merged into master, so this issue can now be closed. The project just needs to have a new release for it work on https://extensions.gnome.org/

That being said, [SUPERCILEX's Clipboard application](https://github.com/SUPERCILEX/gnome-clipboard-history) works just fine on Gnome 42.

**Comment by bam80** [comment]
It was released but still don't see it run.
Extension Manager shows "42" in "Supported Versions", don't know how to see actual Extension version installed.

**Comment by Tudmotu** [comment]
@bam80 Did you install it through https://extensions.gnome.org?

**Comment by bam80** [comment]
@Tudmotu I don't remember. Might be. Recently I tend to install everything via Extension Manager as I don't have https://extensions.gnome.org/ FF addon for a long time already..

**Comment by Tudmotu** [comment]
@bam80 what do you mean "Extension Manager"?
And what linux distribution are you using?

**Comment by bam80** [comment]
https://flathub.org/apps/details/com.mattjakeman.ExtensionManager
Ubuntu 22.04
