### ISSUE TITLE
Settings - Something's gone wrong...

### ISSUE THREAD

**Issue by bbista100** [Tudmotu/gnome-shell-extension-clipboard-indicator#351]
Hi,
Please help. I'm on Ubuntu 20.04. When I click on Settings I get the dialog "Something's gone wrong...We're very sorry..." and I click on Technical Details I get:
----------------------
Error: Could not guess unspecified GValue type

Stack trace:
addKeybinding@/home/lr/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:11
_init@/home/lr/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21
buildPrefsWidget@/home/lr/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
---------------------

```

**Comment by Tudmotu** [comment]
What GNOME version are you using?

**Comment by bbista100** [comment]
Hi,
I'm using GNOME 3.36.8
Thanks.

**Comment by bbista100** [comment]
I've read that I need to use v37 of the extension. Where do I get it here in github? Thanks.

**Comment by Tudmotu** [comment]
I think you can install it from extensions website:
https://extensions.gnome.org/extension/779/clipboard-indicator/

In the dropdown choose the version.
