### ISSUE TITLE
[Feature Request] Option to hide top-bar button, & invoke only by Shortcut

### ISSUE THREAD

**Issue by daudix-UFO** [Tudmotu/gnome-shell-extension-clipboard-indicator#355]
For me, button in top bar is useless, I like to open it by shortcut only, It will be cool if there is option for this

**Comment by TimilsinaBimal** [comment]
+1 for this issue. I think there should be a way to remove the icon from the top bar. Like you, I also like to open it using the keyboard shortcut only.  Did you find any way to remove the icon? I did dig the code but since I don't use TS or JS, I didn't find a way to remove it.

**Comment by daudix-UFO** [comment]
I think other extension do this, we can take code from it

https://extensions.gnome.org/extension/4839/clipboard-history/

**Comment by TimilsinaBimal** [comment]
I try digging the code of this extension too but due to my little knowledge of JS, I couldn't find a way to replicate the method. If you are familiar with JS, you may try it. @Tudmotu Can you please confirm if he can do this or not? Until this extension gets this top panel icon removing feature, I am going to use the clipboard-history extension, which looks similar to this.

**Comment by Tudmotu** [comment]
Thanks for the suggestion. It sounds reasonable. I might get to it some when but as you can tell, things move slow here :)
If anyone wants to contribute they are welcome.

The other extension you mentioned is a fork of this extension that has a couple of other features not implemented here.

**Comment by daudix-UFO** [comment]
> Thanks for the suggestion. It sounds reasonable. I might get to it some when but as you can tell, things move slow here :) If anyone wants to contribute they are welcome.
> 
> The other extension you mentioned is a fork of this extension that has a couple of other features not implemented here.

I personally prefer this extension, fork seems too rough around the edges

**Comment by daudix-UFO** [comment]
Same as #293
