### ISSUE TITLE
"Private mode" can be accidentally enabled while clearing items from history

### ISSUE THREAD

**Issue by openjck** [Tudmotu/gnome-shell-extension-clipboard-indicator#358]
### Steps to reproduce

1. Copy a handful of things
2. Put your mouse over the trash icon for the topmost item in history
3. Rapidly click the mouse

### Actual result

At least on my screen, with my font size, resolution, etc. *Private mode* becomes enabled.

### Expected result

*Private mode* does not become enabled.

### Other notes

It seems that what is happening is that the *Private mode* toggle only listens for a "mouse up" event. When the last trash icon is clicked, the mouse ends up resting above the *Private mode* toggle. When the mouse button is released, a "mouse up" event is fired on the *Private mode* toggle and *Private mode* is therefore enabled.

This can be reproduced using other methods. Instead of clicking on trash can icons at all, open the clipboard indicator menu, press down on the mouse button anywhere in the menu, move the mouse to the *Private mode* toggle, and release the mouse button. *Private mode* will be enabled.

**Comment by SUPERCILEX** [comment]
This how we fixed it: https://github.com/SUPERCILEX/gnome-clipboard-history/issues/66#issuecomment-1133495237
