### ISSUE TITLE
Can cause KDE apps running on GNOME to delay on close

### ISSUE THREAD

**Issue by bulletmark** [Tudmotu/gnome-shell-extension-clipboard-indicator#36]
I raised a bug on the Arch bug-tracker which I have discovered is due to this extension. See https://bugs.archlinux.org/task/48229.

Basically, if this extension is running and you close a KDE app then it delays for about 10 secs before closing and finally prints out a message:

    QClipboard: Unable to receive an event from the clipboard manager in a reasonable time

**Comment by Tudmotu** [comment]
Interesting.. I don't have any KDE apps installed so didn't notice it. Testing it might be difficult cause I assume I need to install the kde base packages. Do you have an example of an app with minimal dependencies that reproduces the issue?

Going over the code, I have no idea what might cause such a thing.. :\

**Comment by bulletmark** [comment]
The only KDE app I use is kmymoney. I just completely purged my system of everything KDE related, rebooted, then re-installed kmymoney alone letting it pull in whatever dependencies it needed. The problem remains. I notice that the first time I run kmymoney after a reboot does not exhibit the problem, it is only seen on 2nd and subsequent runs. I suggest you install kmymoney for a test even though it does pull in quite a few kde and other libs, you can purge them all recursively later (e.g. on arch with pacman -Rs kmymoney).

**Comment by bulletmark** [comment]
Good news, the following two KDE updates occurred on Arch today and the problem is now gone.
~~~~
2016-03-16 07:54 kdelibs                4.14.17-1 -> 4.14.18-1
2016-03-16 07:54 kdebase-runtime        15.12.2-1 -> 15.12.3-1
~~~~
