### ISSUE TITLE
An error occurred when updating

### ISSUE THREAD

**Issue by frs99** [Tudmotu/gnome-shell-extension-clipboard-indicator#368]
An error occurred when updating

**Comment by mirao** [comment]
What error did you get?
I'm getting this during updates of this extension:
![image](https://user-images.githubusercontent.com/12584138/196686292-3a9c1e2c-d0f4-4cf1-a3ef-f742713a997e.png)

and /var/log/syslog logs an error:
```
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[3317]: JS ERROR: Extension clipboard-indicator@tudmotu.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:375:52#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41
```
Here is full log of the update:
```
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]: Archive:  /tmp/BHQ5T1.shell-extension.zip
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/confirmDialog.js
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ar/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ca/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/cs/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/de/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/el/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/es/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/eu/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fa/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fi/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fr_FR/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/hu/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/it/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ja/LC_MESSAGES/ja.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/nl/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/oc/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/pl/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/pt_BR/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ru/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/sk/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/tr/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/uk/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/zh_CN/LC_MESSAGES/clipboard-indicator.mo
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/stylesheet.css
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/LICENSE.rst
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/README.rst
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:    creating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/gschemas.compiled
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/org.gnome.shell.extensions.clipboard-indicator.gschema.xml
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/utils.js
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:  extracting: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[3317]: JS ERROR: Extension clipboard-indicator@tudmotu.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:375:52#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41

```
Reboot or re-logout helps.

**Used SW:**

- Ubuntu 22.04

**Comment by frs99** [comment]
> What error did you get? I'm getting this during updates of this extension: ![image](https://user-images.githubusercontent.com/12584138/196686292-3a9c1e2c-d0f4-4cf1-a3ef-f742713a997e.png)
> 
> and /var/log/syslog logs an error:
> 
> ```
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[3317]: JS ERROR: Extension clipboard-indicator@tudmotu.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:375:52#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41
> ```
> 
> Here is full log of the update:
> 
> ```
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]: Archive:  /tmp/BHQ5T1.shell-extension.zip
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/confirmDialog.js
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ar/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ca/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/cs/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/de/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/el/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/es/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/eu/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fa/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fi/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/fr_FR/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/hu/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/it/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ja/LC_MESSAGES/ja.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/nl/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/oc/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/pl/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/pt_BR/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/ru/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/sk/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/tr/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/uk/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/locale/zh_CN/LC_MESSAGES/clipboard-indicator.mo
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/stylesheet.css
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/LICENSE.rst
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/README.rst
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:    creating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/gschemas.compiled
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas/org.gnome.shell.extensions.clipboard-indicator.gschema.xml
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:   inflating: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/utils.js
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[1076268]:  extracting: /home/mirao/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
> Oct 19 14:04:42 mirao-Precision-7530 gnome-shell[3317]: JS ERROR: Extension clipboard-indicator@tudmotu.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:375:52#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41
> ```
> 
> Reboot or re-logout helps.
> 
> **Used SW:**
> 
> * Ubuntu 22.04

**Comment by frs99** [comment]
**The solution:** Reboot or re-logout helps

thanks @mirao

**Comment by mirao** [comment]
Actually it doesn't work well because the update shouldn't finish with ERROR.
IMHO user should get the message `You need to log out for changes to take effect.` in web interface.
At least re-login is a solution.

**Comment by frs99** [comment]
> 

I don't know but now it works fine after restarting the device

**Comment by mirao** [comment]
BTW the same issue happened to me when upgrading [Freon](https://extensions.gnome.org/extension/841/freon/) extension
```
Nov  1 07:37:12 rzbox gnome-shell[3047]: JS ERROR: Extension freon@UshakovVasilii_Github.yahoo.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:375:52#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41
```
So it seems to be a general issue that can happen with any Gnome extension.
