### ISSUE TITLE
Weird behaviour of shortcut setting

### ISSUE THREAD

**Issue by Pheggas** [Tudmotu/gnome-shell-extension-clipboard-indicator#369]
Hello. I've installed clipboard indicator and when i wanted to change shortcut to open it, it show "New accelerator..." as shortcut key and the whole UI freezes.

Journalctl shows nothing suspicious and to the point. After i close and reopen Gnome Extensions UI, it loads up but i can't open ANY extension's settings.

After i wanted to screenshot the behaviour to this issue, i noticed that the shortcut set itself to ctrl+c as i pressed this combination to copy my region screenshot from Flameshot to clipboard.

![image](https://user-images.githubusercontent.com/9994511/200119901-d95ac618-ae45-43c7-901b-9fa0cdb57b17.png)

Not only i'm unable to set the shortcut to one i want (Windows key + V) but it sets up random key that i press. Not the first one i press.

**Comment by stechio** [comment]
> when i wanted to change shortcut to open it, it show "New accelerator..." as shortcut key and the whole UI freezes.

Same here (Gnome 42.4 with X11 on Ubuntu 22.04.1 LTS).

**Comment by hungify** [comment]
![image](https://user-images.githubusercontent.com/78008509/204079114-bd07dc45-9bae-46b7-a1d5-b8fffcc031ef.png)
Actually, Window + V is used to show the notification list. So it would be best if you replaced it with a new shortcut.
Run `gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Control><Super>x']"` to set `the notification list` with new shortcut `ctrl + window + X`
Can I do that with an `extension-clipboard-indicator`? Why not?
Actually, you can do that with `gsettings set org.gnome.shell.extensions.cliboard-indicator toggle-menu "['<Super>v']"`.
But I have one problem below. I will be creating an issue on this problem soon. 
![image](https://user-images.githubusercontent.com/78008509/204079641-625f687c-8a79-4bc4-8b47-46f6ac845857.png)
