### ISSUE TITLE
Can't set custom keyboard shortcuts from terminal like other extension

### ISSUE THREAD

**Issue by hungify** [Tudmotu/gnome-shell-extension-clipboard-indicator#370]
Thank you for publishing this very useful extension!

I am on Manjaro and GNOME Shell 43.1.
I want to set custom keybinding in extensions from the terminal like  `org.gnome.shell.extensions.dash-to-dock app-control-hotkey"['<Control><Super>x']"` .

But I have one problem when I run `gsettings set org.gnome.shell.extensions.cliboard-indicator toggle-menu "['<Super>v']"` => `No such schema “org.gnome.shell.extensions.cliboard-indicator`.

Here are the different.

- clipboard-indicator

![image](https://user-images.githubusercontent.com/78008509/204079641-625f687c-8a79-4bc4-8b47-46f6ac845857.png)

- dash-to-dock

![image](https://user-images.githubusercontent.com/78008509/204080758-ccf090b4-e544-4f01-8bc2-068f618c64e4.png)

**Comment by Tudmotu** [comment]
I know I am late to reply, but unfortunately I am not familiar with Ubuntu, but in the command you shared you have a typo in the "clipboard-manager" part — you have "cliboard-manager" instead. This might be the issue.

If not, then it's a bug with the extension.

**Comment by hungify** [comment]
Thanks, I will do that and response you as soon as possible.

**Comment by hungify** [comment]
> I know I am late to reply, but unfortunately I am not familiar with Ubuntu, but in the command you shared you have a typo in the "clipboard-manager" part — you have "cliboard-manager" instead. This might be the issue.
> 
> If not, then it's indeed a bug with the extension.

It was the same.

**Comment by hungify** [comment]
> You can use `--schemadir` on the gsettings command as explained in [1](https://askubuntu.com/a/1008879):
> 
> ```shell
> gsettings --schemadir ~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/schemas set org.gnome.shell.extensions.clipboard-indicator toggle-menu "['<Super>v']"
> ```

Cool. It's works for me.

**Comment by Tudmotu** [comment]
Glad it worked out! Thank you @mcornella for helping :slightly_smiling_face:
Closing.
