### ISSUE TITLE
Add a Keyboard shortcut for the extension `

### ISSUE THREAD

**Issue by shahil-leo** [Tudmotu/gnome-shell-extension-clipboard-indicator#371]
The extension is great and very usefull to us but if you add a keyboard shorcut to open the entire set of clipboard and select from there it will be awesome

**Comment by seminarian** [comment]
Yup that would be great!

An awesome thank you to the contributors regardless!!

**Comment by seminarian** [comment]
Did you check out the settings, you can configure a shortcut there to open the panel and select one using the keyboard. Afterwards you can ctrl - V to paste!
