### ISSUE TITLE
Add an option to clear on every boot or similar

### ISSUE THREAD

**Issue by CaptainWinter** [Tudmotu/gnome-shell-extension-clipboard-indicator#372]
This would be useful for someone who brings the laptop around or shares the computer with other people or who just wants to have peace of mind. This could be disabled by default so it won't interfere with the normal operation of the extension.

**Comment by Tudmotu** [comment]
Sounds like a reasonable feature.

Personally I have very little time for adding new features to this extension, but if anyone would like to take this feature on, I will gladly assist with implementation.
