### ISSUE TITLE
Keyboard UI for deleting entries

### ISSUE THREAD

**Issue by PeterJCLaw** [Tudmotu/gnome-shell-extension-clipboard-indicator#375]
Thanks for this useful extension.
Currently there's a keyboard UI to open the clipboard manager and to select the item to paste, however there is no keyboard option to remove items from the list.

It would be great if there was, so that keyboard heavy users could easily remove items.

I suggest that pressing the <kbd>Delete</kbd> key should remove the currently highlighted item, just as if the user had mouse clicked on the bin icon.

**Comment by Tudmotu** [comment]
Makes sense.

**Comment by orpic** [comment]
I want to work on this, can you assign it to me?

**Comment by Tudmotu** [comment]
@orpic thank you for considering contributing!

I would love for you to work on this, but right now the extension is in the process of being migrated to GNOME 45.

This means you would either:
1. Have to wait for GNOME 45 to be released before starting to work on it
1. If you want to start working on it already, you need to branch off from the `gnome45` branch and test it on a system with GNOME 45.beta (one option is to use [GNOME OS Nightly](https://os.gnome.org/) via GNOME Boxes).

Assigning this to you for now. Let me know what you decide.

**Comment by orpic** [comment]
@Tudmotu Thank you for the response!

I will be testing it with GNOME OS Nightly via GNOME Boxes.
As you suggested I will start by connecting the `key-press-event` signal on the actor.

If I encounter any challenges or have questions along the way, I'll be sure to reach out for assistance. 
Thanks again for your support!

**Comment by orpic** [comment]
Hi @Tudmotu

I am ready for a PR.
You can see the changes here: [Link to changes ](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/compare/gnome45...orpic:gnome-shell-extension-clipboard-indicator:gnome45)

1. Pressing the delete button when on a highlighted entry removes the entry
2. After the entry is removed the focus shifts to the next item and if empty then to the private mode

Tested it on GNOME OS Nightly ( via GNOME Boxes )

**Comment by Tudmotu** [comment]
Wow @orpic , that's awesome!
I tested it as well and seems to work. Can you please open a PR so I can merge? :pray:

**Comment by schlagmichdoch** [comment]
@orpic Thanks for implementing this!

One issue:
If I delete an entry of the list via keyboard, the very last item of the list is selected instead of the next item on the list. This makes deleting a little bit confusing. Would be awesome if you could fix that!

Ubuntu 23.10
GNOME 45.rc
Wayland

**Comment by orpic** [comment]
Hi @schlagmichdoch 
Thanks for pointing it out, I intended to move the selection to the next item, seems like I missed it while testing.
Let me take a look at it

**Comment by Tudmotu** [comment]
@orpic please note I am making some change around the area you previously modified so please make sure to merge the latest version.
Also, regarding the bug, maybe look at how the `PopupMenu` class is handling a similar scenario? Not sure if it will work but looks relevant:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/popupMenu.js?ref_type=heads#L903

**Comment by orpic** [comment]
@Tudmotu 
Sure, will take care of the merge, also thanks for the headsup will look into `PopupMenu` class first.

**Comment by orpic** [comment]
Hi @Tudmotu

I have created a PR for the bug, can you take a look at it? [Link to PR](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/396)
