### ISSUE TITLE
Application disables my IntelliJ IDEA hotkeys settings

### ISSUE THREAD

**Issue by nuklea** [Tudmotu/gnome-shell-extension-clipboard-indicator#376]
How to reproduce:
- Open settings
- Try "ctrl+shift+f12" in IDEA: works
- Set keyboard shortcut "next entry" for "ctrl+f12"
- Try "ctrl+shift+f12" in IDEA: **not working**

Clipboard indicator diables my IDE shotrcut in Ubuntu 22.04.

**Comment by Tudmotu** [comment]
Interesting.
When you look at your IDE's shortcut settings, does it look like your shortcut was deleted?

**Comment by nuklea** [comment]
No. Shortcut exists

вт, 31 янв. 2023 г. в 00:51, Yotam Bar-On ***@***.***>:

**Comment by Tudmotu** [comment]
Did you try setting the clipboard shortcut to anything other than ctrl+f12?

**Comment by nuklea** [comment]
i set its value to nothing: IDE shortcut works

ср, 1 февр. 2023 г. в 11:05, Yotam Bar-On ***@***.***>:

**Comment by Tudmotu** [comment]
Interesting. Ok, glad it works for you now.
Unfortunately I don't have IntelliJ to debug this issue. I have a feeling it is some bug with GNOME's shortcut module, but can't say for sure. It might be resolved "of itself" in a future GNOME release.
Keeping this issue open in case others experience it as well.
