### ISSUE TITLE
Allow cache sizes bigger than 16384 kb

### ISSUE THREAD

**Issue by aria3ppp** [Tudmotu/gnome-shell-extension-clipboard-indicator#378]
Right now it is not possible to save the contents of a file with 2600 lines or 70 kbyte (in my case) on clipboard
Allow users to  set `Max cache file size (kb)` values bigger than limited 16384

**Comment by samyosm** [comment]
What do you think could be a great size? I'll try to make the maximum 100MB for now.

**Comment by aria3ppp** [comment]
Actually i have no opinion on a specific upper limit for cache size
But i checked a similar extension with maximum cache size of 16383MB
Also i do not have any idea on how an upper limit can effect performance btw

**Comment by Tudmotu** [comment]
In the past, it affected the performance of the entire operating system to the point where we had reports of crashes.

Not sure if this has improved in more recent GNOME versions.

If anyone would like to make the change and test it out, I would appreciate it.
