### ISSUE TITLE
please make it  support with gnome 44

### ISSUE THREAD

**Issue by Mdsarowarhossain** [Tudmotu/gnome-shell-extension-clipboard-indicator#383]
please resale a new version which support gnome 44

**Comment by francescor** [comment]
I'm on the same boat :)


btw: thank you for your code, which should be included in Gnome, really!

**Comment by SamuelBorn** [comment]
I also need it :) its by far the best clipboard indicator.

**Comment by faha1999** [comment]
![image](https://user-images.githubusercontent.com/54038576/233234612-b2be4d3c-3a97-48d5-b147-5d2a4d5195b4.png)

Update please ASAP.

**Comment by Tudmotu** [comment]
I don't have 44 installed yet so can't personally test it.

Can anyone manually update the metadata.json and confirm it works?

**Comment by Tudmotu** [comment]
Package has been updated on e.g.o for GNOME 44.

**Comment by faha1999** [comment]
Now it works pitty fine. Thank you :)
