### ISSUE TITLE
Shortcut can't be set back to Control-F9

### ISSUE THREAD

**Issue by osamuaoki** [Tudmotu/gnome-shell-extension-clipboard-indicator#386]
I am on GNOME43 (Debian Bookworm) and this extension v45: 9d51ca1 ("Merge pull request #382 from cewbdex/patch-1", 2023-04-22).

I can set or disable shortcut to most key combination but not to Control-F9 etc.  Somehow combination with Control seems to be lost and key without Control is recorded.  (It took me a while to realize Backspace key use for disabling key bind.)

![keybinds](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/7339387/970590b6-739e-4a8f-8897-decce9cb65e6)

**Comment by Tudmotu** [comment]
Interesting, thank you for reporting.

Is Control-F9 set to some other shortcut in you GNOME settings (Settings > Keyboard > Keyboard Shortcuts)?

**Comment by osamuaoki** [comment]
No.

FYI: 
Where you use:
```
  │   │   │   │   let accelString = Gtk.accelerator_name(key, mods);
  │   │   │   │   SettingsSchema.set_strv(id, [accelString]);

```
In my extension in which I set shortcut, I use
```
  │   │   │   │   const binding = Gtk.accelerator_name_with_keycode(
  │   │   │   │   │   null,
  │   │   │   │   │   keyval,
  │   │   │   │   │   keycode,
  │   │   │   │   │   mask
  │   │   │   │   );
  │   │   │   │   // console.log(`  binding = ${binding}`);
  │   │   │   │   settings.set_strv(`${name}`, [binding]);
```
following practices of other extensions.

I don't suffer funny issue of ALT-F9.

**Comment by osamuaoki** [comment]
I mean Control-F9

**Comment by osamuaoki** [comment]
Here are links to similar shortcut setting extensions

- https://github.com/jqno/gnome-happy-appy-hotkey.git
- https://github.com/osamuaoki/inputmethod-shortcuts (mine)

**Comment by osamuaoki** [comment]
Hi,  This is FYI  (I may have found better reference code.)

I found
- https://github.com/eonpatapon/gnome-shell-extension-caffeine.git

More specifically
- https://github.com/eonpatapon/gnome-shell-extension-caffeine/tree/master/caffeine%40patapon.info/preferences

This seems to be another one and follows exactly the same logic as C code: 
- https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/main/panels/keyboard/keyboard-shortcuts.c

I am thinking to follow gnome-control-center since it is most tested.

**Comment by Tudmotu** [comment]
> FYI: Where you use:
> 
> ```
>   │   │   │   │   let accelString = Gtk.accelerator_name(key, mods);
>   │   │   │   │   SettingsSchema.set_strv(id, [accelString]);
> ```
> 
> In my extension in which I set shortcut, I use
> 
> ```
>   │   │   │   │   const binding = Gtk.accelerator_name_with_keycode(
>   │   │   │   │   │   null,
>   │   │   │   │   │   keyval,
>   │   │   │   │   │   keycode,
>   │   │   │   │   │   mask
>   │   │   │   │   );
>   │   │   │   │   // console.log(`  binding = ${binding}`);
>   │   │   │   │   settings.set_strv(`${name}`, [binding]);
> ```

Can you try implementing this is and opening a PR? :pray:

**Comment by osamuaoki** [comment]
I am a newbie javascript programmer and not familiar with ES5 style coding around Lang-thing.  Since I just finish verifying the details using dummy extension code for my extension, let me wait a bit before creating PR.  

I see bugs in the current gjs gdk for GTK4 document generation etc.  I will work on them first.

**Comment by SidonTheTroll** [comment]
Can I just know where the shortcuts are mentioned so that i can change them?

**Comment by Tudmotu** [comment]
@SidonTheTroll open the clipboard indicator, click on "settings" and at the bottom you can change the shortcuts: 
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/506487/ae6c2e9d-a35d-47af-b061-c7d4cc513f77)

**Comment by SidonTheTroll** [comment]
@Tudmotu Well, I meant in the config files. Even if I can't reset it to default (I'm running low on braincells), I can just assign another hotkeys.

**Comment by Tudmotu** [comment]
@SidonTheTroll not sure I understand. You can change it from the settings.
To edit a shortcut, click on the right where it says "Ctrl+9" then insert the new shortcut.
To delete a shortcut press backspace.

There is no config file for the shortcuts.

**Comment by SidonTheTroll** [comment]
I get the point. Have been using another for weeks. Just wanted to go back to the original configs but can't assign ctrl any of the shortcut

**Comment by osamuaoki** [comment]
I used dconf-editor to erase the current custom setting to regain as-installed default.

**Comment by osamuaoki** [comment]
Go to `/org/gnome/shell/extensions/clipboard-indicator/`
Then to `/org/gnome/shell/extensions/clipboard-indicator/toggle-menu`

- Click ERASE key button
- Click Apply button

FYI: I am on GNOME on wayland

**Comment by Tudmotu** [comment]
Thank you @osamuaoki using some of your references I managed to re-implement the key binding interface.

It will be released & fixed as part of the GNOME 45 version.

If you'd like to help me test it out, it's available on the `gnome45` branch (requires a system with GNOME 45.beta, e.g. GNOME OS via Boxes).
