### ISSUE TITLE
Port to ESM

### ISSUE THREAD

**Issue by bbhtt** [Tudmotu/gnome-shell-extension-clipboard-indicator#388]
GNOME Shell switched to ESM as part of 45 https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1499. This means all extensions will be broken unless ported.

See the GUADEC talk: https://youtu.be/qaZuQO0bK-M?t=21013

The official ones have already been ported https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/commit/a9114473751fd022a5208618a8c9bb488651a48a

This breaks backwards compat in a way: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version

You'll have to upload multiple versions (if it is ported) to target older GNOME versions.

**Comment by Tudmotu** [comment]
Thank you @bbhtt for letting me know.

Is this only about replacing the dependencies with `import * as ... from '...'`?
Is there anything else that needs changing?

**Comment by bbhtt** [comment]
> Thank you @bbhtt for letting me know.
> 
> Is this only about replacing the dependencies with `import * as ... from '...'` or is there anything else that needs changing?
> 
> And how can we test this before 45 is released?
> 

Probably.

45.beta is out I think and includes the changes.

I can't comment too much on the code but feel free to drop by in #extensions:gnome.org (Matrix) that's where extensions/shell experts are in, GNOME discourse etc.

**Comment by alephnull** [comment]
There's a guide at https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by Tudmotu** [comment]
Thank you @alephnull

**Comment by Tudmotu** [comment]
I've migrated the extension to GNOME 45, would greatly appreciate testing & bug reports :pray: 
You can try it on GNOME 45.beta by cloning the `gnome45` branch:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/gnome45

**Comment by bbhtt** [comment]
Awesome ❤️

Seems to work. Will report anything if I see.
