### ISSUE TITLE
GNOME 45 Support 

### ISSUE THREAD

**Issue by craftergarage** [Tudmotu/gnome-shell-extension-clipboard-indicator#389]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by Tudmotu** [comment]
I'm still not sure how to test it. I would like to avoid upgrading my own system before it's out of beta.

Is there any docker image for GNOME 45?

**Comment by GerryT11** [comment]
FYI, here is lots of information on the changes in Gnome 45 for extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/ . There is also the link to the Gnome 45 porting guide (https://gjs.guide/extensions/upgrading/gnome-shell-45.html). For early testing, they mention "You can test your extensions by downloading the latest [GNOME OS](https://os.gnome.org/) and trying your extension there."

Thanks for the great Clipboard Indicator extension!

**Comment by Tudmotu** [comment]
Thank you @GerryT11 ! :pray: 

I've already migrated the extension and I'm currently testing it.
If you'd like to help me out and test it as well, I would greatly appreciate it. Here is the branch:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/gnome45

**Comment by GerryT11** [comment]
> Thank you @GerryT11 ! 🙏
> 
> I've already migrated the extension and I'm currently testing it. If you'd like to help me out and test it as well, I would greatly appreciate it. Here is the branch: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/gnome45

Sorry, so far I was not yet able to successfully run GnomeOS in Gnome-Boxes to test the extension. 
I hope someone else can help out with testing, too!

**Comment by Tudmotu** [comment]
Thank you for trying @GerryT11  :pray: 
It's ok, a couple of people helped test it out and an official version has already been approved on e.g.o :slightly_smiling_face:
