### ISSUE TITLE
The new notification is useless. 

### ISSUE THREAD

**Issue by person666** [Tudmotu/gnome-shell-extension-clipboard-indicator#39]
It shows up only sometimes, and get's stuck on screen often after pressing f12 or f11. It is broken. Most of the time it stays in the notification tray so I can't see what I just selected with f12 or f11.

**Comment by Tudmotu** [comment]
Thanks for reporting! :)
I believe I fixed the issue - uploaded it to e.g.o, so hopefully it'll be approved in the next days.

**Comment by Tudmotu** [comment]
Available on e.g.o
