### ISSUE TITLE
Private mode dimming gone in gnome-45 branch

### ISSUE THREAD

**Issue by bbhtt** [Tudmotu/gnome-shell-extension-clipboard-indicator#390]
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/62639087/6a02ddca-94e6-401d-af9d-223466d9fa49)

On a59954fb8a8595caeadb16fc255973463674f81d

GNOME 45.beta Wayland Fedora 39 beta

**Comment by Tudmotu** [comment]
Do you mean the indicator icon in the top bar?

**Comment by bbhtt** [comment]
Yea

**Comment by bbhtt** [comment]
Thanks
