### ISSUE TITLE
Copied text aren't displayed after switching to private mode and back

### ISSUE THREAD

**Issue by bbhtt** [Tudmotu/gnome-shell-extension-clipboard-indicator#391]
Switch to private mode and switch back
Copy something
Clipboard is blank

On a59954fb8a8595caeadb16fc255973463674f81d

It starts working after logging out and logging back in

GNOME 45.beta Wayland Fedora 39 beta

**Comment by Tudmotu** [comment]
I can't seem to be able to reproduce this. Do you have any more details on how this happens?

**Comment by bbhtt** [comment]
Looks like it works, I'm closing. If I see it happen again I'll reopen. Thanks.

**Comment by bbhtt** [comment]
Hmm This happened again I think this is somehow related to the UI getting stuck https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/393
