### ISSUE TITLE
Clear history doesn't work

### ISSUE THREAD

**Issue by bbhtt** [Tudmotu/gnome-shell-extension-clipboard-indicator#392]
Nothing is cleared

[8458d18b04.webm](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/62639087/51d106e5-305e-44f8-8abf-0929570ac0e0)

On a59954fb8a8595caeadb16fc255973463674f81d

GNOME 45.beta Wayland Fedora 39 beta

**Comment by bbhtt** [comment]
Upon further testing looks like everything except the last copied item is cleared.

**Comment by Tudmotu** [comment]
Yeah this is an existing feature request.
I would implement it but I am focused on the migration still and not sure I'll have time to do so.
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/281
