### ISSUE TITLE
Private mode UI is updated only for the first time

### ISSUE THREAD

**Issue by bbhtt** [Tudmotu/gnome-shell-extension-clipboard-indicator#393]
Log in and switch to private mode

Looks like this:

![d20dffa15b](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/62639087/d6598071-9eec-47c1-92bd-4a2935841160)

Switch back and switch again to private mode

Looks like this now:

![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/62639087/af8c7e94-0601-4447-955e-62a20e0df74a)

On a59954fb8a8595caeadb16fc255973463674f81d

GNOME 45.beta Wayland Fedora 39 beta

**Comment by bbhtt** [comment]
This seems to happen only some times

**Comment by Tudmotu** [comment]
Should be fixed in the latest commit to `gnome45`

**Comment by bbhtt** [comment]
Thanks
