### ISSUE TITLE
doesnt seem to work with gnome 45 beta

### ISSUE THREAD

**Issue by hrdkmishra** [Tudmotu/gnome-shell-extension-clipboard-indicator#395]
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/87580981/2ae0381b-81b3-436d-a434-fbb46d677df8)

i downloaded via gnome extension

**Comment by Tudmotu** [comment]
Thank you for testing this out! :pray: 

Would you mind please running the following in your terminal (preferably right after a login) and see if you can find the error there, with the filename and line of the exception?
```console
$ journalctl -f /usr/bin/gnome-shell
```

Thanks!

**Comment by schlagmichdoch** [comment]
Can confirm this works on `GNOME Shell 45.rc` since updating a few days ago.

**Comment by Tudmotu** [comment]
Thank you @schlagmichdoch . Did you install it from extensions.gnome.org or from Git?

**Comment by schlagmichdoch** [comment]
from extensions.gnome.org

**Comment by Tudmotu** [comment]
Got it. Thank you! :pray:

**Comment by wuqso** [comment]
> ![image](https://user-images.githubusercontent.com/87580981/268185286-2ae0381b-81b3-436d-a434-fbb46d677df8.png)
> 
> i downloaded via gnome extension

I have the same problem. I'm using Fedora 39 prerelease and gnome shell 45.rc. I installed this extension from extensions.gnome.org and can see all settings.

**Comment by wuqso** [comment]
The error is there when running

$ journalctl -f /usr/bin/gnome-shell

**Comment by Tudmotu** [comment]
@wuqso can you please share the error message and stack trace?

**Comment by Valeryan24** [comment]
Hi, same error message here : 
Ubuntu 23.10 beta
GNOME Shell 45.rc
Clipboard Indicator 51 (installed from Gnome extensions site)

journalctl -f /usr/bin/gnome-shell
sept. 17 14:49:43 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:43 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:43 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:45 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:46 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:47 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:50 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:52 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:53 valeryan24-desktop gnome-shell[2739]: Meta.Rectangle is deprecated, use Mtk.Rectangle instead
sept. 17 14:49:53 valeryan24-desktop gnome-shell[2739]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

**Comment by Tudmotu** [comment]
Thank you all. There is indeed an issue on GNOME 45.rc, which does not exist on 45.beta.1.

Working on fixing it now.

**Comment by Tudmotu** [comment]
@wuqso @hrdkmishra @Valeryan24 Thank you all for reporting this!
I've uploaded a new version to e.g.o.
Would really appreciate if you could install v52 and let me know if the extension works :pray:

**Comment by Valeryan24** [comment]
Version 52 works well for me on Ubuntu and Gnome 45.rc, thanks for the quick upgrade !

**Comment by Tudmotu** [comment]
Thank you for testing it out @Valeryan24 :pray:

**Comment by rmader** [comment]
Hi - while version 52 mostly works for me, opening the settings is still broken with the following message:

The settings of extension clipboard-indicator@tudmotu.com had an error:
```
TypeError: (intermediate value).SpinRow is not a constructor
```

Stack trace:
```
Settings@file:///home/robert/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:27:27
fillPreferencesWindow@file:///home/robert/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:12:28
_loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Tudmotu** [comment]
Thanks for reporting @rmader. I can't reproduce this but I will look into it.
Can you please tell me the exact version of GNOME you are running? (`gnome-shell --version`)
Also if this a fresh install, or did you upgrade Clipboard Indicator from an older version?

**Comment by rmader** [comment]
Sorry, my bad. `SpinRow` is a libadwaita 1.4 feature which I didn't have on my system yet - and while it's not required by GS 45, it's practically part of the Gnome 45 release. After updating that the settings work again.

**Comment by Tudmotu** [comment]
@rmader thank you for the update! Glad to hear it works now :slightly_smiling_face:

**Comment by wuqso** [comment]
The new version works but the clipboard is always empty. What's the problem?

**Comment by Tudmotu** [comment]
@wuqso Do you see any errors in `journalctl /usr/bin/gnome-shell`?
Also does pasting not work either?

**Comment by wuqso** [comment]
All errors are libinput errors. Pasting works fine with the middle button of the mouse.

**Comment by wuqso** [comment]
The clipboard is also always empty in the extension 'clipman' on my system. Do I need any extra apps?

**Comment by Tudmotu** [comment]
@wuqso `ctrl+v` doesn't paste?

**Comment by wuqso** [comment]
After some trials, I found I need to use the right button of the mouse to 'copy' the text into the clipboard. I would prefer to copy the text into the clipboard by just highlighting the text.

**Comment by Tudmotu** [comment]
@wuqso yes this is one of the oldest and most requested features for this extension: #8 
I might try to implement it some when soon. Now that we had to drop support for older versions, it should be easier.
If anyone else would like to give it a stab, I'll happily merge a PR. If anyone is interested please reach out to me via email and I'll explain how it should probably work. It won't be simple though.
