### ISSUE TITLE
Deleting history is not persistent (Clipboard entries are back after laptop wakes up from sleep)

### ISSUE THREAD

**Issue by vanitasvitae** [Tudmotu/gnome-shell-extension-clipboard-indicator#40]
Im using Debian 8.4 and installed your extension from extensions.gnome.org.
When I delete the history of clips, close my laptop lid, open it up again later the history is filled again. This is critical concerning passwords that were in the history.

**Comment by vanitasvitae** [comment]
Nevermind, I just saw that there was a newer version available that had this behaviour fixed :+1:

**Comment by Tudmotu** [comment]
Glad to hear it works for you :)
If you have any more issues, don't hesitate to report them. Thanks!
