### ISSUE TITLE
Language files not working

### ISSUE THREAD

**Issue by xiaozhangup** [Tudmotu/gnome-shell-extension-clipboard-indicator#401]
I updated my extensions and Gnome and then my extension languages all changed to English. My desktop is in Chinese.
And, the repository language files seem to be out of date

**Comment by Tudmotu** [comment]
Thank you for reporting this.
Are you using GNOME 45?

**Comment by xiaozhangup** [comment]
> Thank you for reporting this. Are you using GNOME 45?

Yes

**Comment by Tudmotu** [comment]
Can you please run `journalctl -f /usr/bin/gnome-shell` in your terminal and see if you get any errors from clipboard-indicator by chance?

I will take a look in the next couple of days hopefully.

**Comment by xiaozhangup** [comment]
> Can you please run `journalctl -f /usr/bin/gnome-shell` in your terminal and see if you get any errors from clipboard-indicator by chance?
> 
> Also are you using the latest version from extensions.gnome.org?
> 
> I will take a look in the next couple of days hopefully.

Yes, the latest extension

**Comment by xalt7x** [comment]
I have the same issue.
`journalctl -f /usr/bin/gnome-shell`
doesn't seem to have anything related.
Maybe it has something to do with [translations initialization](https://gjs.guide/extensions/development/translations.html#initializing-translations).
BTW, [https://github.com/SUPERCILEX/gnome-clipboard-history/pull/147](Clipboard history GNOME 45 port) uses translations.

**Comment by Tudmotu** [comment]
Thanks for reporting.
Technically everything seems fine and configured properly.
Not sure why you are not seeing translations applied. Is this the only extension where this happened to you?
Did you try restarting your computer after updating the extension?

**Comment by xalt7x** [comment]
> Is this the only extension where this happened to you?
> Did you try restarting your computer after updating the extension?

Yes.
I think something had been missed in GNOME 45 port. As I mentioned in the previous post, the fork of this extension with the same translation structure ("Clipboard History") doesn't have this issue.

**Comment by Tudmotu** [comment]
@xiaozhangup and @xalt7x thank you both for reporting this. Version 57 on e.g.o is supposed to fix this issue.
Please let me know that it works :slightly_smiling_face: :pray:

**Comment by xalt7x** [comment]
@Tudmotu 
The new version works for me. Thanks!

**Comment by xiaozhangup** [comment]
> @xiaozhangup and @xalt7x thank you both for reporting this. Version 57 on e.g.o is supposed to fix this issue. Please let me know that it works 🙂 🙏

Work fine for me, thanks!

**Comment by Tudmotu** [comment]
Thank you for confirming :pray:
