### ISSUE TITLE
Missing Git tags

### ISSUE THREAD

**Issue by lubo** [Tudmotu/gnome-shell-extension-clipboard-indicator#402]
[Clipboard Indicator - GNOME Shell Extensions](https://extensions.gnome.org/extension/779/clipboard-indicator/) states that versions 50 and later exist, yet the last tag in Git is [v47](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v47). Please, add the missing tags.

**Comment by Tudmotu** [comment]
The problem is the latest version, which supports GNOME 45, completely break backwards compatibility, and since most distributions don't have GNOME 45 yet, the extension would break for them. So I am waiting until 45.1 is released (which is when most distros should add the new GNOME version).

I will merge the `gnome45` branch to master and will create tags once it's out.

For now, if you are a package maintainer, you can use the `gnome45` branch, assuming the distro you are packaging for has GNOME 45 already.

**Comment by lubo** [comment]
Sorry, but I don't understand what prevents you from tagging. Tagged commits don't have to be in the main branch. The versions exist, they are published and we should be able to tell to which versions they correspond. Do you wanna do rebase or something similar? I'd say that's not advisable at this point, since you've already published existing revisions.

**Comment by Tudmotu** [comment]
This is a very popular GNOME extension. It is packaged by many contributors to many different distros. I am not aware of all the different packages, but I know some of them automatically fetch the latest tag without manually testing. If you accidentally install the new version on a distro that does not support GNOME 45, it will break. When this extension breaks, I tend to get many, many emails. So I am taking the safe route.
GNOEM 45.1 should be out in 1-2 weeks, so I will tag it then.

**Comment by jonian** [comment]
The missing tags for gnome 45 have resulted in broken arch linux (AUR) package. I agree that tags/releases should be created when they are released. Package maintainers should take care when they have to update their package version. That should not be any of your concerns. Just my opinion.

**Comment by Tudmotu** [comment]
Ok I see Ubuntu has also already released GNOME 45.
The main one that still doesn't support it is Fedora, but from what I can tell they should release any time now.
I will do a quick check what other distros already support 45.

**Comment by Tudmotu** [comment]
Ok looking at https://repology.org/project/gnome-shell/versions
It seems all major distributions already support 45.0.

Thank you @jonian and @lubo, I will tag the releases now and will not wait for 45.1.

**Comment by Tudmotu** [comment]
I tagged v54.
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/v54

**Comment by jonian** [comment]
Thanks @Tudmotu! I updated the AUR package.
