### ISSUE TITLE
Truncating text by visible characters rather than String.prototype.length?

### ISSUE THREAD

**Issue by Expertcoderz** [Tudmotu/gnome-shell-extension-clipboard-indicator#404]
The `length` property of a JavaScript string corresponds to the number of UTF-16 code units that comprise the string.

Whereas, certain user-perceived characters (actually graphemes) are made up of multiple contingent code units or code points.

These characters, when they lie at the limit of text to be truncated, may be cut up as a result.

Demonstration with the UN flag (`🇺🇳`) copied to clipboard, on the `gnome45` branch with `MAX_TOPBAR_LENGTH` set to 3:

![Screenshot from 2023-10-17 13-30-16](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/81153405/7edab945-58c3-47f6-829c-bdfbbb0835fb)

This happens because `🇺🇳` is actually `U+1F1FA` + `U+1F1F3`, which takes up 4 code units, causing the character to be truncated. This is probably not an expected outcome on the user's end.

Here's with [a fix](https://github.com/Expertcoderz/gnome-shell-extension-clipboard-indicator/commit/2121a87c98099f083d296616d40c53d98c6cc638) applied:

![Screenshot from 2023-10-17 13-27-00](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/81153405/67368dfc-ee24-4279-bbf3-b55660dfae12)

I will submit a pull request if such a proposed new behavior is desired.

**Comment by Tudmotu** [comment]
Thank you for reporting and implementing a fix!
Can you please use the `gnome45` branch as the base for you PR? :pray:
