### ISSUE TITLE
[BUG] since GNOME 45, cannot copy strings from Firefox

### ISSUE THREAD

**Issue by mattia-b89** [Tudmotu/gnome-shell-extension-clipboard-indicator#408]
since GNOME 45,  
when I copy text from web-pages, clipboard history append this tag:  
`<meta http-equiv="content...`

from GNOME 45 using Firefox 119 on Arch Linux

---

screenshot:  
![Untitled](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/545463/18685c1f-4ffd-4533-b2a7-bd502bf4c42e)

**Comment by Tudmotu** [comment]
Yeah I've noticed this as well. I believe it's actually a Firefox bug/unwanted feature.
The reason this didn't happen before GNOME 45 is because GNOME started supporting mimetypes for clipboard content and Firefox for some reason uses `text/html`.
I will look into it, not sure if it'll be easy to fix.

**Comment by mattia-b89** [comment]
thanks @Tudmotu for your concern about;  
I confirm the issue with Epiphany 45, too  

I can add two more things:  

1. when you **paste** (the broken content, according to our extension) **into** another application*, it works as should: the "_clean_" content is copied into;  

_*I tried to copy into Firefox, Chromium, gedit, Gnome-console_

2. if you **copy from** Chromium/Chrome, it does not have this issue;

**Comment by Tudmotu** [comment]
@mattia-b89 can you please check version v56? :pray: 
It should fix both this and #409

**Comment by brunolpsousa** [comment]
I was facing this issue with Firefox and Brave (with wayland flags).
I've been running v56 for a little while now and it seems to have resolved the issue for me.
Thanks!

**Comment by mattia-b89** [comment]
Fixed with v56!
thanks
