### ISSUE TITLE
[BUG] since GNOME 45, links from Chromium do not show up

### ISSUE THREAD

**Issue by mattia-b89** [Tudmotu/gnome-shell-extension-clipboard-indicator#409]
since GNOME 45,  
when I copy links from Chromium's address bar,  
they do not show up in clipboard history  
but I can paste content elsewhere;

from GNOME 45 using Chromium 118.0.5993.117-1 on Arch Linux

**Comment by Tudmotu** [comment]
Thank you for reporting.
I will have to test it out on Chromium. Arch + Chrome seems to work.

**Comment by mattia-b89** [comment]
I can reproduce it with Chrome, too  
launched from terminal with: `google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland`  

The interesting thing is that content is copied (you can paste it elsewhere) but our extension does not show it up in the list

**Comment by mattia-b89** [comment]
v56 does not **completely** fix this issue for Chromium,  
but for Chrome, only **partially**:  

- if I copy URL with mouse (Right Click -> Copy) it works
- if I use keyboard shortcut (CTRL+C) it does not work

---

_Honestly I do not know if we are facing a different issue (since I haven't noticed about mouse VS keyboard shortcut detail and Chromium VS Chrome difference)_  
_or it is the same;_  
_anyhow, I tested mouse VS keyboard shortcut  behaviour with gedit and in this scenario everything works as should,_  
_probably we are in front of a Chrome-specific issue (since Chromium does not suffer of that) so we can close this and open a new one;_
