### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by CanonContraption** [Tudmotu/gnome-shell-extension-clipboard-indicator#41]
Is there any potential for making this extension compatible with GNOME on Wayland? Right now it loads properly, but nothing shows up in the menu.

Haven't had a chance to look at the code myself, but I think that would be a nice addition

**Comment by freeroot** [comment]
It works for me on Fedora 25/Wayland. Maybe things has changed since june.

**Comment by hari-rangarajan** [comment]
Nopes. Definitely don't see it working on wayland. @freeroot maybe you are not running on wayland.

**Comment by Tudmotu** [comment]
I'm on Arch with GNOME 3.22 + Wayland, and it works for me. What OS are you running @hari-rangarajan ?
What version of GNOME? There were issues with earlier versions of GNOME+Wayland.

**Comment by CanonContraption** [comment]
Sorry for taking so long to get back to this, moved to the KDE world again. I waffle between desktops a lot. I don't know what changed but it works 100% now. If you don't know whether you're running Wayland or not, check using the looking glass. To do so:

open Nautilus (Files), Epiphany (Web), GEdit (Text Editor), or any other core GNOME app (if in doubt, stick to one of those)
<Alt>+<F2>
type lg
hit <Enter>
click 'Windows'
Click on the window title for the GNOME app you just launched.
You should see MetaWindow{X11|Wayland}
If it is MetaWindowX11 you are running X.
If it is MetaWindowWayland you are running Wayland.

@Tudmotu yes, it works in Arch GNOME 3.22.
@hari-rangarajan  If you're running an older version of GNOME my only advice is upgrade, your Wayland support is out-of-date. Sorry I couldn't be of more help here, but unfortunately this kind of support is still new enough that there are still real problems for a lot of people due to their version of GNOME simply being a version or two old.
