### ISSUE TITLE
Gnome 45, v56 - not working, only "Text will be here"

### ISSUE THREAD

**Issue by earchsay** [Tudmotu/gnome-shell-extension-clipboard-indicator#411]
Hi, and cheers for the fantastic extension first of all!
All of a sudden it stopped working, symptoms are the same as in closed issue #400 
Icon and "Text will be here" on the top bar, no actions no nothing.

`journalctl -f /usr/bin/gnome-shell` occasionally comes up with:
`JS ERROR: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data @ file:///home/khalimon/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:92:51`

Interestingly, for the second user on the same laptop everything keeps working just fine.

**Comment by Tudmotu** [comment]
Hmm, it seems like your registry file is corrupted.
Can you please check if you have the file `/home/khalimon/.cache/clipboard-indicator@tudmotu.com/registry.txt`?
If it exists, try renaming it to `/home/khalimon/.cache/clipboard-indicator@tudmotu.com/registry.backup.txt` and logout/login to GNOME. This will remove your clipboard history.

Let me know if the extension works after that.

**Comment by earchsay** [comment]
> Hmm, it seems like your registry file is corrupted. Can you please check if you have the file `/home/khalimon/.cache/clipboard-indicator@tudmotu.com/registry.txt`? If it exists, try renaming it to `/home/khalimon/.cache/clipboard-indicator@tudmotu.com/registry.backup.txt` and logout/login to GNOME. This will remove your clipboard history.
> 
> Let me know if the extension works after that.

Thank you! There was a zero length registry.txt, renamed it and now the clipboard indicator works again.

**Comment by gentakojima** [comment]
The same thing happened to me recently—a registry.txt file with zero length. I'm not sure how it occurred, but if this is a recurring issue, it might be a good idea to implement an automatic check for empty registry.txt files. If detected, the file could be deleted, with the event logged and optionally a notification sent to the user.

**Comment by Tudmotu** [comment]
Might be related to #502
