### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by ahadfarajpour** [Tudmotu/gnome-shell-extension-clipboard-indicator#416]
software information
ubuntu 23.10
64-bit
kernel linux 6.5.0-10-generic
GNOME Shell 45.0
Error
SyntaxError: import declarations may only appear at top level of a module
Stack trace:
 @file:///home/lost/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:5:19
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by hasan-sh** [comment]
same issue

**Comment by Tudmotu** [comment]
What version of the extension do you have?

**Comment by ahadfarajpour** [comment]
> What version of the extension do you have?

How can I find the plugin version?

**Comment by Tudmotu** [comment]
@ahadfarajpour did you install the extension through e.g.o?
Check if you have an update available here:
https://extensions.gnome.org/local/

**Comment by ahadfarajpour** [comment]
> @ahadfarajpour did you install the extension through e.g.o? Check if you have an update available here: https://extensions.gnome.org/local/

Yes, it is installed and it is the latest version
I got this problem since I upgraded Ubuntu to 23.10
Before the upgrade was working perfectly

**Comment by cesarFrias** [comment]
I had the same issue when upgrading to fedora 39.
Gnome-shell version 45.1

**Comment by cesarFrias** [comment]
I did nothing and it came back to work! Like magic. Sorry for the noise

**Comment by Tudmotu** [comment]
Anyone who is experiencing this issue, could you please share the output of the following commands:
```console
$ gjs --version
```

```console
$ cat ~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json
```

And also please try restarting your computer (or at least logout of GNOME) and see if the issue persists?
Thanks!

**Comment by CrossedCarpet** [comment]
tried to edit the code, logged out and it's working. Don't think it's related to me editing it though...

**Comment by Tudmotu** [comment]
Thanks @CrossedCarpet. I think the re-login is what solves it. From the `metadata.json` file you shared it seems the extension was an old version. It only got actually updated once you logged-in again.

I am closing this issue for now. If anyone still has issues after a restart / re-login, feel free to open.
