### ISSUE TITLE
Question: How to install extension on Gnome 43?

### ISSUE THREAD

**Issue by livan3li** [Tudmotu/gnome-shell-extension-clipboard-indicator#420]
hi, i couldn't figure it out how to install extension while main page of repo says you should install v47 for Gnome 43 but latest version is 44 on repo. I checked extension page([link](https://extensions.gnome.org/extension/779/clipboard-indicator)) on gnome extension page but it's not same as repo content. Hence it's note possible to install extension since there is no makefile. 

Can you help?

**Comment by livan3li** [comment]
I've managed to install by going to extension official web site and https://extensions.gnome.org/extension/779/clipboard-indicator

1. Download the zip
2. Extract it's content to `~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com`
3. Log out the from system and re-login
4. Now it's time to enable extension by command `gnome-extensions enable clipboard-indicator@tudmotu.com`

Enjoy!

Thanks everybody for contributing to this project.

**Comment by Tudmotu** [comment]
Happy to see it worked for you! :pray: 
Closing this :slightly_smiling_face:
