### ISSUE TITLE
Where can I find Clipboard Indicator V47 ?

### ISSUE THREAD

**Issue by Shuaiwei-dash** [Tudmotu/gnome-shell-extension-clipboard-indicator#421]
I am using GNOME 42.5, according to the [GNOME Version Support](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator#-gnome-version-support), I need to install Clipboard Indicator version 47, but I can't find this version in the [release](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases), so which version should I use now or where I can find this version?

**Comment by Tudmotu** [comment]
Hi @Shuaiwei-dash,
You can find it on e.g.o — you need to choose your GNOME version in the dropdown:
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/506487/e205a2a1-fb77-4f9b-9116-214249e41eeb)

Link to extension page:
https://extensions.gnome.org/extension/779/clipboard-indicator/

**Comment by Shuaiwei-dash** [comment]
> Hi @Shuaiwei-dash, You can find it on e.g.o — you need to choose your GNOME version in the dropdown: ![image](https://private-user-images.githubusercontent.com/506487/285820696-e205a2a1-fb77-4f9b-9116-214249e41eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODA0MTIsIm5iZiI6MTcwMTA4MDExMiwicGF0aCI6Ii81MDY0ODcvMjg1ODIwNjk2LWUyMDVhMmExLWZiNzctNGY5Yi05MTE2LTIxNDI0OWU0MWVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMDE1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmMwNTE4NWFhM2U3YmNjN2ExYjMwMDM5NjhhMGI3YzdlZmU5NGMxNGMzMDcyZmVlYjFlYTFjNDI2ODJjODg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EoZHrW36jhkZo9pF4MjwRh1C6Goth_miGPXJi7nK_YM)
> 
> Link to extension page: https://extensions.gnome.org/extension/779/clipboard-indicator/

found it, thank you!
