### ISSUE TITLE
If you had a virgin for Windoze you would become wealthy beyond words

### ISSUE THREAD

**Issue by UbuntuSteve** [Tudmotu/gnome-shell-extension-clipboard-indicator#427]
Please make one for Windoze.  Some of us have to run it on some machines because of needed programs etc.

**Comment by Tudmotu** [comment]
My ETH address: 0xE1338d3D972D7304DcB66334EFFa21f652E16025

Make me rich and I'll re-open. Till then I can't do a Windoze virgin unfortunately :slightly_smiling_face:
