### ISSUE TITLE
Clip board indicator is not working, and shows a message "Text will be here" prompt

### ISSUE THREAD

**Issue by nPrevail** [Tudmotu/gnome-shell-extension-clipboard-indicator#432]
I was moving some Home files, and I accidentally moved **.config, .cache, and .local** system files from an old system into my new Home directory, overwriting the system files. Now, Clipboard Indicator fails to open when I try clicking on the extension from the toolbar, and the clipboard now shows "Text will be here," as demonstrated in this video:

[Screencast from 2024-01-04 23-16-40.webm](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/57690587/b5a2d652-f3eb-484d-8d70-09481d0f762c)

What can I do to reverse this for clipboard indicator? How can I delete the "tainted" files that impacts clipboard indicator?

**Comment by nPrevail** [comment]
I just solved it!

./Home/.cache/clipboard-indicator@tudmotu.com/registry.txt caused this error.

Removing the registry.txt, restarting Clipboard-Indicator, allowed clipboard-indicator to create a new registry.txt.

**Comment by Tudmotu** [comment]
Happy you manged to solve this :pray:
