### ISSUE TITLE
Cannot use "win" as hotkey in the keyboard shortcuts

### ISSUE THREAD

**Issue by OliEfr** [Tudmotu/gnome-shell-extension-clipboard-indicator#434]
For me it is not possible to use the "Win"-button as the hotkey. Combinations with "ctrl" and "alt" work, though.

See also #205

**Comment by Tudmotu** [comment]
I don't think these issues are related.
It does seem to work for me:
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/506487/bd0aea24-db29-4998-a94f-4095ad7bb3fd)

What GNOME version and Linux distribution are you using?

**Comment by OliEfr** [comment]
Thanks for getting back.

The issue was on my side, sorry. I tried to use a hotkey that was already used by ubuntu (super+v) https://help.ubuntu.com/stable/ubuntu-help/shell-keyboard-shortcuts.html.en | https://help.ubuntu.com/stable/ubuntu-help/keyboard-shortcuts-set.html.en

I disabled it in ubuntu, and not it works for ClipboardIndicator.

BTW: Thanks for creating one of the best productivity tools for ubuntu.

**Comment by Tudmotu** [comment]
Thank you for using and reporting issues :slightly_smiling_face: :pray:

**Comment by Sispheor** [comment]
Hello, I'm on Ubuntu 24.04 and i doesn't work. 
I've disabled the default shortcut `super+v` and set it in clipboard manager but pressing the combination doesn't work then.

**Comment by OliEfr** [comment]
Maybe other applications are using the super+v shortcut already?

Are other shortcuts working for you, if so, which ones?

**Comment by Sispheor** [comment]
OK after a restart 😅.
Working fine now ! Thank you for your quick support  and for this very useful app !
