### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by matdave** [Tudmotu/gnome-shell-extension-clipboard-indicator#439]
Fedora 40 has been branched. Currently this plugin does not work in Gnome 46. I tried manually editing the metadata but wound up with  additional type errors.

**Comment by Tudmotu** [comment]
Please try branch `gnome46` and let me know if it works?
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/gnome46

Thanks :slightly_smiling_face:

**Comment by matdave** [comment]
It works! Thanks @Tudmotu

**Comment by sidt4** [comment]
Doesn't work in GNOME 46. I have v59 installed. 

Just displays `"Text will be shown here..."` in top bar. Clicking on it does nothing.

**Comment by sidt4** [comment]
> Doesn't work in GNOME 46. I have v59 installed.
> 
> Just displays `"Text will be shown here..."` in top bar. Clicking on it does nothing.

Appears to be due to https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/447. Works fine now in GNOME 46.
