### ISSUE TITLE
Full screen to the wrong screen with Remmina

### ISSUE THREAD

**Issue by ComputingFroggy** [Tudmotu/gnome-shell-extension-clipboard-indicator#44]
Hi,

a strange bug: when using _Remmina_ (RDP client) to connect to a terminal server from a secondary monitor, the full screen session is opened on the primary monitor (instead of the secondary).
If I disable  Clipboard indicator extension, all is OK.

I have managed to get _Remmina_ and _Clipboard indicator_ working together by switching on and off Private mode, several times (and emptying the history) ! ? ! ? !

**Comment by Tudmotu** [comment]
Closing this. If anyone still has issues please open a new ticket.
