### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by LiasOne** [Tudmotu/gnome-shell-extension-clipboard-indicator#445]
Gnome 46
Previous entry & Next entry Not Working

**Comment by ZauJulio** [comment]
Same here

**Comment by ConstantMan** [comment]
Same here

**Comment by NickBelhomme** [comment]
same here

**Comment by scr4sh** [comment]
same here

**Comment by Tudmotu** [comment]
Thank you all for reporting.

Does the action itself not work, or does it not work to set the shortcut?

**Comment by scr4sh** [comment]
You can set the shortcut, but when using it, that is, when you press in my case "shift + f10" to go to the previous one, and with f11 to go to the next one, it doesn't work, but they are set.

**Comment by Tudmotu** [comment]
Yes, forgot to update here that I believe this is related to #444 . I have a fix prepared, will release it soon.

**Comment by LiasOne** [comment]
Fixed, Thank you.
