### ISSUE TITLE
Scroll Bar is Inaccessible To Mouse

### ISSUE THREAD

**Issue by TheWiseNoob** [Tudmotu/gnome-shell-extension-clipboard-indicator#466]
Couldn't find this issue mentioned elsewhere. My scroll bar is inaccessible to mouse clicks for scrolling. I have to use my scroll wheel to scroll. You can see it hidden behind the first highlighted history entry.

![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/7541485/621ee33e-54b4-4a3f-90c8-5ff4bca40e92)

Using the latest version on Arch with GNOME 46.

**Comment by Tudmotu** [comment]
Yeah, I think it's from GNOME 46 that's why it was not reported yet. I noticed it as well.
Thank you for reporting! :pray:
