### ISSUE TITLE
After suspend to ram the icon is not grey anymore (private mode)

### ISSUE THREAD

**Issue by mobybit** [Tudmotu/gnome-shell-extension-clipboard-indicator#47]
Steps to reproduce

1. activate private mode > grey icon
2. suspend to ram
3. resume > white icon

Private mode is activ, but the clipboard list shows the last entries.

Fedora 24, Gnome 3.20

**Comment by Tudmotu** [comment]
Thanks for reporting! :)
I'll look into that
