### ISSUE TITLE
Optional notification

### ISSUE THREAD

**Issue by optama** [Tudmotu/gnome-shell-extension-clipboard-indicator#48]
Notification on copy might be a good visual aid but in other cases not preferred - is there a simple way to turn it off?

**Comment by Tudmotu** [comment]
Not at the moment.
What would you imagine as a "simple way"?
Is a checkbox in the settings ok?

**Comment by Skatox** [comment]
Yes, please add a checkbox in the settings panel. This notification is annoying.

**Comment by Tudmotu** [comment]
@optama - Nice! I see you're working on a fix? :smiley:
If you need any help or something, just let me know!

**Comment by optama** [comment]
#49 is a proposal for toggling of notification on copy.

**Comment by Tudmotu** [comment]
Merged @optama's PR, will upload to e.g.o :smiley:

**Comment by ocafebabe** [comment]
How long does it take for the update to be deployed on Gnome Extensions? I reinstalled the extension this morning but I still don't see the new option!

**Comment by Cybolic** [comment]
Mine just updated to include this fix. I cannot tell you how relieved I am that this was added, the notification was driving me crazy during coding sessions! :D
Thank you so much @optama !
