### ISSUE TITLE
The gaps between all menus in the top bar have become larger

### ISSUE THREAD

**Issue by HenTaku0** [Tudmotu/gnome-shell-extension-clipboard-indicator#483]
![截图 2024-07-13 13-22-27](https://github.com/user-attachments/assets/62631fd7-4107-4922-bc5f-e3565b25cb5b)
![截图 2024-07-13 13-22-18](https://github.com/user-attachments/assets/41ff817b-1185-44cb-a32c-034105f94407)
This isn't an issue with individual applications, all menus are affected, including the shutdown menu

**Comment by TheWiseNoob** [comment]
Yeah I'm seeing this as well. This is a result of the css fix for the scroll bar being covered up not targeting only the extension's menu.

**Comment by TheWiseNoob** [comment]
@Tudmotu I've created a PR that fixes this: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/484


**Before:**
![image](https://github.com/user-attachments/assets/b1118fd6-1749-4dc5-a60e-e4dee1fa8d3e)
![image](https://github.com/user-attachments/assets/8ed1a270-c2db-4168-a423-4a53aa20fc73)


**After:** 
![image](https://github.com/user-attachments/assets/3093ba90-d1da-4774-8f21-94d1626357ba)
![image](https://github.com/user-attachments/assets/c5f869c0-9c5e-46d0-9ff1-172cf491f276)
