### ISSUE TITLE
Copied image doesn't show up on list

### ISSUE THREAD

**Issue by sans-clue** [Tudmotu/gnome-shell-extension-clipboard-indicator#487]
When I right-click -> copy an image from a browser, the image doesn't show up on the list.

The image is on the clipboard, I can paste it wherever but once I copy something else I cannot select that image again.

**Comment by ZnMnCr** [comment]
My Ubuntu version is 20.04 and my shell version is 3.36.8, which also reports this problem.

**Comment by Tudmotu** [comment]
@ZnMnCr, images are only supported on GNOME 45 and above unfortunately.
@sans-clue are you also using an older GNOME version?

**Comment by sans-clue** [comment]
> @ZnMnCr, images are only supported on GNOME 45 and above unfortunately. @sans-clue are you also using an older GNOME version?

Apologies for the late response. Yes, I'm on Ubuntu 22.04 which uses GNOME 42.9 it seems.
Closing this ticket.
