### ISSUE TITLE
Request for GNOME 47 Support

### ISSUE THREAD

**Issue by GhaziRiyadh** [Tudmotu/gnome-shell-extension-clipboard-indicator#488]
Dear Clipboard Indicator Team,

I am writing to request your support for GNOME 47 in your extension. I have been a long-time user of your extension and have found it to be very helpful in customizing my GNOME desktop.

I am currently using GNOME 47 and have noticed that the extension is no longer compatible with this version. This has made it difficult for me to continue using your extension and has limited my ability to customize my desktop.

I understand that developing and maintaining extensions can be time-consuming, but I believe that adding support for GNOME 47 would be a valuable addition to your extension. Many GNOME users have upgraded to version 47, and having your extension available for this version would benefit a large number of users.

I would be happy to assist in any way I can to help you add support for GNOME 47. If you need any additional information or have any questions, please do not hesitate to ask.

Thank you for your time and consideration.

Sincerely,

**Comment by Tudmotu** [comment]
Version 65 now supports GNOME 47
