### ISSUE TITLE
This plugin seems to not work properly under gnome47.

### ISSUE THREAD

**Issue by myueqf** [Tudmotu/gnome-shell-extension-clipboard-indicator#493]
I hope this message finds you well. I've been using your plugin with 
gnome47 and it seems to have encountered some hiccups in its performance. 
I appreciate all the hard work that goes into creating these tools for us. 
Could you maybe take a look at it? It would be great if we could smooth 
out any kinks soon. Thank you very much for your contributions!

**Comment by ken-kuro** [comment]
Manually apply the changes in #492 or wait until the PR is merged

**Comment by ken-kuro** [comment]
Fyi, the file should be at `~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json` just add 47 entry to the gnome version array. Work fine on my latest Arch Linux

**Comment by myueqf** [comment]
> Fyi, the file should be at `~/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/metadata.json` just add 47 entry to the gnome version array. Work fine on my latest Arch Linux

Thank you very much, it has been solved. I also use archlinux

**Comment by Tudmotu** [comment]
Version 65  now supports GNOME 47
