### ISSUE TITLE
Clipboard Indicator not working, only shows "Text will be here" besides the icon in Ubuntu 24.04 (GNOME Shell 46)

### ISSUE THREAD

**Issue by shahshaiq** [Tudmotu/gnome-shell-extension-clipboard-indicator#494]
Clipboard Indicator is not functioning as expected on Ubuntu 24.04 under GNOME Shell version 46. The indicator only displays `Text will be here` beside the clipboard icon, and no actual clipboard content is shown. The indicator seems to fail in updating or retrieving clipboard data

**Comment by Tudmotu** [comment]
Can you please provide the following details:
- Clipboard Indicator version
- GNOME version
- Wayland or X11

Thanks

**Comment by BIRO-IS** [comment]
Can confirm this behaviour for:

- Ubuntu 24.04.
- Gnome 46
- X11

Turning the extension off and on several times in the extension manager brings it back.
Thank you!
