### ISSUE TITLE
Clipboard Notification

### ISSUE THREAD

**Issue by NawfalTachfine** [Tudmotu/gnome-shell-extension-clipboard-indicator#50]
Ever since the last update a notification pops up whenever something is copied into the clipboard. It can be a bit annoying, especially for frequent copy/pasting. It would be great to be able to disable that from the extension options.
Great work on the extension by the way. I can't live without it now :)

**Comment by woohooatb** [comment]
Now you can deactivate it from preference menu menu.

**Comment by Skatox** [comment]
Did you uploaded to gnome extensions? I don't see the option nor the update.

**Comment by Tudmotu** [comment]
@Skatox yes, the new version is uploaded, but still unreviewed. It will probably take a couple  more days to get reviewed on e.g.o.

**Comment by woohooatb** [comment]
I'm on 3.21.91 so I had to manually install it anyway. :D

**Comment by Paviluf** [comment]
I will be great if gnome extensions can be updated to allow us to disable the notification.
Thanks !

**Comment by simonbcn** [comment]
I agree, the notifications are a pain. They should be able to be disabled in the configuration.

**Comment by Tudmotu** [comment]
Update was approved, you guys can install it now 😃

**Comment by NawfalTachfine** [comment]
Works like a charm. Thanks a lot!
