### ISSUE TITLE
Can't install extension even manually.

### ISSUE THREAD

**Issue by skullscream** [Tudmotu/gnome-shell-extension-clipboard-indicator#53]
I tried installing it just by turning the slider to 'ON' on firefox. Pops up the 'Install' dialog, I press install but nothing happens. I clone this repository and move it to /usr/share/gnome-shell/extensions and do alt+f2 -> r and go to gnome tweak tool to select it but it's not there.

Other extensions work perfectly fine and install with no issues.

Antergos 64bit
Gnome 3.22.1

**Comment by RaphaelRochet** [comment]
Can you try changing 3.20 to 3.22 in file "metadata.json" ?

**Comment by skullscream** [comment]
Tried changing 3.20 to 3.22 and adding 3.22 but still no luck.

**Comment by Xazzzi** [comment]
Same problem, Gnome 3.22.1

**Comment by Tudmotu** [comment]
For me personally, the extension works with 3.22. 
Technically, we should add "3.22" to the "shell-version" field in the metadata.json file. I didn't do that yet because it worked for me and I (probably wrongfully) assumed it is not necessary anymore.

To test that this is the issue, follow these steps:

1. edit the "metadata.json" file: add "3.22" to the array in the "shell-version" field, and save.
1. press Alt+F2
1. a prompt will open
1. insert "r"
1. press Enter
1. Open gnome-tweak-tool, and enable the extension there

Can anyone confirm this works? I will try to upload a new version with this change anyway, because I guess it's best practice.

**Comment by skullscream** [comment]
Like I sad, adding 3.22 doesn't work. I add it like this, write out and exit. Then do Alt+F2 r and......nothing.
http://i.imgur.com/7smmCYy.png
http://i.imgur.com/zUYiPUn.png

**Comment by Tudmotu** [comment]
can you please run ``journalctl -f``, then restart the shell, and see if there are any messages with "gnome-shell" or "clipboard-indicator" in them?

**Comment by skullscream** [comment]
I do get this from journalctl -f

`Oct 28 17:12:50 arch gnome-shell[736]: JS ERROR: Could not load extension gnome-shell-extension-clipboard-indicator: Error: uuid "clipboard-indicator@tudmotu.com" from metadata.json does not match directory name "gnome-shell-extension-clipboard-indicator"
                                       createExtensionObject@resource:///org/gnome/shell/misc/extensionUtils.js:125
                                       ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:169
                                       wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                       bind/<@resource:///org/gnome/gjs/modules/lang.js:95
                                       collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
                                       ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
                                       wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                       _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
                                       enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
                                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
                                       init@resource:///org/gnome/shell/ui/extensionSystem.js:346
                                       _initializeUI@resource:///org/gnome/shell/ui/main.js:216
                                       start@resource:///org/gnome/shell/ui/main.js:125
                                       @<main>:1`

**Comment by Tudmotu** [comment]
hm.. can you try installing it like it says in the  readme? put it in .local/, with the right  directory name?
im also gonna upload a version with the shell-version fix, and maybe you'll be able to install it then. 😃

**Comment by Tudmotu** [comment]
I uploaded it to e.g.o, so you can maybe try installing it the usual way again?

**Comment by skullscream** [comment]
> I uploaded it to e.g.o, so you can maybe try installing it the usual way again?
That made it working. Thanks!

**Comment by Tudmotu** [comment]
Awesome 😃  👍 
im closing this issue
