### ISSUE TITLE
Feature: autocopy on selection

### ISSUE THREAD

**Issue by NawfalTachfine** [Tudmotu/gnome-shell-extension-clipboard-indicator#54]
Hello friends,

There's a neat feature in terminator that enables autocopying any selection to the clipboard and I was wondering if it would be possible to generalize it to the entire desktop environment through our beloved extension here. 
Please let me know what you think :)

Cheers!

**Comment by Tudmotu** [comment]
that would be an awesome feature, and we actually already have two issues for this: #34 , #8 
Unfortunately, I did not have time to actually implement something like that yet :\

**Comment by dmig** [comment]
@Tudmotu please, close this one and other duplicates of #8 not to confuse people.

**Comment by NawfalTachfine** [comment]
@dmig there :)
