### ISSUE TITLE
Add Clear Clipboard option

### ISSUE THREAD

**Issue by eliandoran** [Tudmotu/gnome-shell-extension-clipboard-indicator#55]
In the extension's context menu, there's the _Clear history_ menu item, but I think a _Clear clipboard_ option next to it would prove useful. Clearing the data currently stored in clipboard (as well as its corresponding entry in history) would benefit privacy, among other things.

Thanks.

**Comment by dermitdemdino** [comment]
Me too.

**Comment by Tudmotu** [comment]
I think the "clear history" should also clear the clipboard. Do you think two separate buttons are better?

**Comment by eliandoran** [comment]
Hello. That is not a bad idea either.

The thing is I have grown quite accustomed to using the clipboard history, and I use it all the time in my web development endeavours. Although I believe having the _Clear history_ also clear the clipboard would not be the most intuitive option, and let's see why:

> Alice has a clipboard full of useful snippets (code snippets that she uses during development, paths and whatnot), but has also copied the FTP deployment password. The password is of severe importance, meaning that it must not ever be stored in plain text or plain sight. She forgot to start the _Private mode_ in the Clipboard Indicator.

How does she remove that password? One method is copying another random text and deleting the history entry of the item. But what if the current entry had a remove button just like the other ones have?

The other method would be the one that you proposed, and that is being able to clear the entire history, but that would result in loss of productivity since she would lose all her code snippets and other things she used during development.
