### ISSUE TITLE
Can't open preferences

### ISSUE THREAD

**Issue by toupeira** [Tudmotu/gnome-shell-extension-clipboard-indicator#57]
Nothing happens when I try to open the extension's preferences through Tweak Tool or extensions.gnome.org

I can see these messages with `journalctl -f`:

```
gnome-shell-ext[8547]: JS ERROR: TypeError: imports.extensionPrefs is undefined
unknown[8547]: Execution of main.js threw exception: JS_EvaluateScript() failed
```

I'm running Gnome 3.22.2 on Debian sid.

**Comment by Tudmotu** [comment]
Does it work with clicking on "Settings" in the clipboard indicator menu? (below the history list)

For me opening via Tweak Tool and e.g.o works, I'm on Arch with 3.22.2.
Is there anything more of interest in the logs?

**Comment by toupeira** [comment]
@Tudmotu sorry looks like I upgraded Gnome at some point and didn't restart, after a reboot the settings now work fine :)

**Comment by Tudmotu** [comment]
Great to hear, thanks for updating! 😃
