### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by amivaleo** [Tudmotu/gnome-shell-extension-clipboard-indicator#61]
Hi,
I would like to give the italian translation for your clipboard extension.
I hope you will appreciate it. :)

Cya!

[it.tar.gz](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/files/934537/it.tar.gz)

**Comment by Tudmotu** [comment]
Thanks @amivaleo!
But could you maybe do it in the form of a Pull Request?

**Comment by amivaleo** [comment]
I did it @Tudmotu.
At least... I hope so. I've never used github so much before. I can see the pull request and the files are there.

Please, let me know if I did something wrong. :)

**Comment by Tudmotu** [comment]
I merged you PR #62, and will test it later. Will upload it to the extensions website soon. Thanks!
