### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by dirosis** [Tudmotu/gnome-shell-extension-clipboard-indicator#65]
Hello, I translated this extension in greek, where can I upload the archives?

**Comment by Tudmotu** [comment]
Hi! 😄 
Thanks for the interest!
You need to create a Pull Request that will add the new translation files to this repository.
If you need help with opening a pull request or anything else, let me know :)

**Comment by dirosis** [comment]
I need some help indeed. I've never before created a pull request. Do I need to create a new branch in order to later merge it with the master branch?

**Comment by dirosis** [comment]
I need some help indeed. I've never before created a pull request. Do I need to create a new branch in order to later merge it with the master branch?
