### ISSUE TITLE
Paste on middleclick doesn't work

### ISSUE THREAD

**Issue by mdicke2s** [Tudmotu/gnome-shell-extension-clipboard-indicator#67]
Pasting on applications context menus as well as by using CTRL-V works fine. It pastes the topmost string on clipboard-indicator. However, if you use middleclick for pasting it behaves differently. Then the last copied string is pasted (even if another one is selected in clipboard-indicator)

**Comment by Tudmotu** [comment]
Hi there @mdicke2s! :)
Thanks for reporting this. Unfortunately, this might be a bit difficult to implement.

The middle-click paste is actually not the same clipboard as the CTRL-V clipboard. This extension only handles the CTRL-V clipboard at the moment.
There are several discussions on how to handle the PRIMARY (selection) clipboard. See #8, #34, #54.

**Comment by mdicke2s** [comment]
Ok, thanks for your feedback. From my perspective "synchronize clipboards" sounds lika a valid solution.

**Comment by Tudmotu** [comment]
I'm closing this in favor of #8
