### ISSUE TITLE
Menu toggle not working

### ISSUE THREAD

**Issue by carmanaught** [Tudmotu/gnome-shell-extension-clipboard-indicator#68]
I've recently pieced together an extension to toggle menus (credit to you for some of your code from this extension that I used), but in testing and trying to figure out how to toggle the menus, I found that with 'Keyboard shortcuts' enabled and the 'Toggle the menu' shortcut specified the menu is only opened, not closed, and doesn't actually toggle. For reference, I'm using GNOME 3.24.

Rather than a check for whether the menu is visible and then opening/closing, you could probably just use the menu toggle method in the _toggleMenu function:

`_toggleMenu: function() {
    this.menu.toggle();
}`

I wasn't sure if it made sense to create a pull request for such a small change, or if there's a legacy reason for the code such as the toggle only being added since a particular version of GNOME, though I get the impression it's been there for a while.

**Comment by Tudmotu** [comment]
Hi @carmanaught !
Yes, if you don't mind, please open a pull request :smiley:
I would highly appreciate it. This has been an issue for some time, and there's no good reason why ^_^

**Comment by carmanaught** [comment]
Pull request #69 created to fix the function used by the 'Toggle the menu' keybinding.

**Comment by carmanaught** [comment]
Since this fix has been merged I've closed the issue. I've made the change locally myself, but when it updates on e.g.o everyone else will receive it anyway.
