### ISSUE TITLE
How to remove the following...

### ISSUE THREAD

**Issue by haydenjames** [Tudmotu/gnome-shell-extension-clipboard-indicator#76]
How to remove...
-- private mode (not just disable, but remove the toggle switch)
-- dropdown icon to the right of the clipboard icon.

How to remove both of these?

Thanks

**Comment by Tudmotu** [comment]
It is not possible to remove these currently. If you like, I can help you implement a configuration in the settings that will allow to hide both these features. :)

**Comment by darginyegor** [comment]
private mode is a good feature i think. but this new dropduwn arrow looks horrible and totally unnecessary. it ruins the whole look of right part of the topbar. smb please at least add an option to disable it to extension settings.

**Comment by Tudmotu** [comment]
Closing this since it's stale. If anyone would like to send a PR for a switch in the settings that hides the toggle, I welcome it. :slightly_smiling_face:
