### ISSUE TITLE
Previous entry delay

### ISSUE THREAD

**Issue by umpirsky** [Tudmotu/gnome-shell-extension-clipboard-indicator#80]
Steps to reproduce:

- `Ctrl + F11`
- `Ctrl + V`

If you do it quickly, it will paste current entry instead of previous. If you wait a couple of seconds, it works correctly.

There is a delay when going to previous/next entry, not sure why.

**Comment by capaj** [comment]
@umpirsky I suspect it might get fixed if you just decrease the

![image](https://user-images.githubusercontent.com/1305378/47560465-93fbdf00-d918-11e8-99ae-01a4d47bd96b.png)

but it won't allow lower values than 500 so I guess we can't be sure if a value of 50 or 100 would help.

**Comment by capaj** [comment]
oh actually I tried putting there 5000 and it took 5 seconds to update after hitting the key.
So it's definitely the refresh dependent.

**Comment by umpirsky** [comment]
Yes, I decreased to 1000 and it works fine. Forgot to share, sorry.

**Comment by capaj** [comment]
I would keep this open-it should be possible to work right after the hot key press.

**Comment by umpirsky** [comment]
True.
