### ISSUE TITLE
[feature request] option to change keyboard shortcuts

### ISSUE THREAD

**Issue by JeffMelton** [Tudmotu/gnome-shell-extension-clipboard-indicator#81]
I'd love to be able to set my own keyboard shortcut. If this is already available, I haven't discovered it yet.

**Comment by Tudmotu** [comment]
hi @JeffMelton  :)
you can change the keyboard shortcuts in the extension settings.

**Comment by JeffMelton** [comment]
This is my week for dumb questions, I guess. 🙈 How do you change them?

**Comment by Tudmotu** [comment]
You open the clipboard menu, and click on "settings"
Then, at the bottom of the settings page you have the shortcuts. You can click on the key (the right side) and it will allow you to set a new shortcut.

I see though that for some reason it doesn't allow to set ctrl+fn keys. Weird. but other than that seems to work.
