### ISSUE TITLE
"Disable cache file" must delete registry.txt cache file

### ISSUE THREAD

**Issue by freeroot** [Tudmotu/gnome-shell-extension-clipboard-indicator#89]
Because items which are on registry.txt cache file comes back to my clipboard indicator history, even after weeks, even if history is cleared.

**Comment by JPvRiel** [comment]
@freeroot have you tried "Clear History"? I think that would delete most items. Except the last one: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/79.

Agree, it would be better if "Disable cache" implicitly did this too, and relates to https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/58.

**Comment by freeroot** [comment]
I didn't use "Clear History" because it's no related to this issue. This issue is related to "disable cache file" option.

I don't know why it were not added to the option which is, nevertheless, great for the moment.

**Comment by Tudmotu** [comment]
I would not like people to accidentally delete their cache file by clicking on this thing (just to see what it does, or by accident).
We can maybe do it, only if we add a popup that appears once you click on the "disable cache file" warning you that it will delete the current history.
But the "clear history" should work i think, definitely if you do it before going into "memory only" mode.

**Comment by freeroot** [comment]
Click on "disable cache file" doesn't delete the current history, I still have all my items copied on clipboard indicator.
Moreover, if I "disable cache file", then delete manually registry.txt and finally "enable cache file", registry.txt is create again with the current history. So, there is no way to lose your clipboard at all in my opinion.

Delete the registry file will delete "ghost clipboard cache" what is expected with this option.

**Comment by JPvRiel** [comment]
@freeroot agree, the behaviour could be better. It's a question of finding time to tweak it so that disable cache file prompts you to delete history. 

However, we might be in need of a major refactoring to have the option to not cache to file anyhow. A simple gnome lock and unlock is causing the extension to lose the in-memory history (separate issue!), so disable cache has other quite bad implications... Haven't found time to investigate/test further.

**Comment by freeroot** [comment]
Useless since https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/commit/5ce531154bb294a0205c2ada9a61ee5704033c13
