### ISSUE TITLE
Where is saved (file or database) the history of clipboard?

### ISSUE THREAD

**Issue by juusechec** [Tudmotu/gnome-shell-extension-clipboard-indicator#93]
Hello, I want to recover a copied text and via gnome interface I can't get registry before 50th one older.

Thanks

**Comment by Tudmotu** [comment]
There is no infinite history saved anywhere. There is the registry file which is located at ``~/.cache/clipboard-indicator@tudmotu.com/registry.txt`` but it contains what you see in the indicator menu.
You can increase your registry size through  the settings, but it might cause slowdowns.

**Comment by juusechec** [comment]
Thanks !
