### ISSUE TITLE
New search feature fails to filter history

### ISSUE THREAD

**Issue by JPvRiel** [Tudmotu/gnome-shell-extension-clipboard-indicator#97]
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/90 search feature does not work for me (Ubuntu 16.04.3 LTS, GNOME Shell 3.18.5)

I tested with cache enabled and disabled (in case that was the issue).

Expected: When I type in the search bar, the list of clipboard entries become filtered.
Actual: No filtering, no change of entries displayed.

I tried pressing 'enter' and I tried more than 3 characters. Typically, most interactive search bars don't start until at least 3 n-grams (characters to match in sequence) are available.

P.S. Liked the idea behind https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/90 - useful feature!

**Comment by nhinds** [comment]
If I type something in the search box and then run `journalctl | tail` (or just run `journalctl` and scroll to the bottom of my screen), the following errors are being thrown by this extension:

```
Nov 05 13:09:41 my-hostname gnome-shell[1984]: JS ERROR: TypeError: text.includes is not a function
                                                  ClipboardIndicator<._onSearchTextChanged/<@/home/my-username/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:204:33
                                                  ClipboardIndicator<._onSearchTextChanged@/home/my-username/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:202:13
                                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Nov 05 13:09:41 my-hostname gnome-shell[1984]: JS ERROR: TypeError: text.includes is not a function
                                                  ClipboardIndicator<._onSearchTextChanged/<@/home/my-username/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:204:33
                                                  ClipboardIndicator<._onSearchTextChanged@/home/my-username/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/extension.js:202:13
                                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
```

It looks like `.includes` doesn't exist as a function on javascript strings in my version of gnome-shell.

My versions: Ubuntu 17.04, gnome-shell 3.24.2, gjs 1.48.3-0ubuntu0.1

According to the [gjs NEWS file](https://github.com/GNOME/gjs/blob/master/NEWS#L146), the `includes()` method on `String` was added in 1.49.4, which is newer than the version I use. Maybe it only works in the latest Gnome Shell.

**Comment by Tudmotu** [comment]
Oh, oops! I used some feature that doesn't exist in earlier gnome-shells! 
Will fix that asap.

**Comment by tanmayrajani** [comment]
I got an update today for the extension and this seems to be fixed! :clinking_glasses:

**Comment by Tudmotu** [comment]
Yup, this should be fixed now. Thanks for confirming! :smiley:
